# Feature engineering & Modeling
Last updated: _2022.06.08_

In [1]:
import pandas as pd

import matplotlib.pyplot as plt

In [2]:
df_data = pd.read_csv('output/dataset_churn_labeled_th8_20260609.csv')

In [3]:
print("There are {:,} rows and {:} columns in the raw data.".format(df_data.shape[0], df_data.shape[1]))
print("The dataset contains data from {:} to {:}.".format(df_data['summary_date'].min(), df_data['summary_date'].max()))

There are 545,488 rows and 54 columns in the raw data.
The dataset contains data from 2021-01-01 to 2022-12-31.

In [4]:
df_data['summary_date'] = pd.to_datetime(df_data['summary_date'])
df_data['registration_date'] = pd.to_datetime(df_data['registration_date'])
df_data['firstdeposit_createddate'] = pd.to_datetime(df_data['firstdeposit_createddate'])
df_data['is_churned'] = df_data['is_churned'].astype(int)

In [5]:
df_data.sort_values(['accountid', 'summary_date'], ascending=True, inplace=True)

## Feature engineering

In [6]:
# decided to use GBP as base
columns_to_keep = [
    'accountid',

    # date related
    'summary_date', 'registration_date', 'firstdeposit_createddate',
    
    # categorical
    'agp_brand', 'reporting_region', 'market', 'reg_prod', 'foundation_category', 'account_tier', 'category', 'activity_channel', 'secondary_product', 'bet_type', 'productgroup',
    
    # numerical
    'plc_turnover_gbp', 'plc_turnover_gbp_rcash', 'plc_turnover_gbp_bonus', 'plc_betcount',
    
    'stl_turnover_gbp', 'stl_turnover_gbp_rcash', 'stl_turnover_gbp_bonus',
    'stl_ggr_gbp', 'stl_ggr_gbp_rcash', 'stl_ggr_gbp_bonus', 
    
    #'stl_betting_duty', 'stl_licence_fee', 'stl_tax', 'stl_partnerfee',
    
    'stl_betcount',
    
    'deposit_gbp', 'withdrawal_gbp',
    
    'bonus_costs', 'realcash_costs', 'bonusfunds_costs', 'bonus_costs_accurrency', 'bonusfunds_costs_accurrency',

    'is_churned'
]

In [7]:
df_data = df_data[columns_to_keep].copy()

### Date

In [8]:
account_age = (
    df_data.groupby("accountid")
        .agg(
            registration_date=("registration_date", "first"),
            last_summary_date=("summary_date", "max")
        )
    )

account_age['account_age_in_days'] = (
    account_age["last_summary_date"] - account_age["registration_date"]
).dt.days

account_age = account_age.reset_index()
account_age.columns = ['accountid', 'registration_date', 'last_summary_date', 'account_age_in_days']
account_age = account_age[['accountid', 'registration_date', 'account_age_in_days']].copy()

In [9]:
account_age[:5]

   accountid registration_date  account_age_in_days
0  666989420        2020-10-03                  684
1  666989923        2020-10-03                  507
2  666990238        2020-10-03                  471
3  666999616        2020-10-08                  726
4  667005177        2020-10-10                  562

In [10]:
time_to_first_deposit_age = (
    df_data.groupby("accountid")
        .agg(
            registration_date=("registration_date", "first"),
            first_deposit_date=("firstdeposit_createddate", "first")
        )
    )

time_to_first_deposit_age['time_to_first_deposit_age'] = (
    time_to_first_deposit_age["first_deposit_date"] - time_to_first_deposit_age["registration_date"]
).dt.days

time_to_first_deposit_age = time_to_first_deposit_age.reset_index()
time_to_first_deposit_age.columns = ['accountid', 'registration_registration', 'first_deposit_date', 'time_to_first_deposit_age']
time_to_first_deposit_age = time_to_first_deposit_age[['accountid', 'time_to_first_deposit_age']].copy()

In [11]:
time_to_first_deposit_age[:5]

   accountid  time_to_first_deposit_age
0  666989420                          0
1  666989923                          0
2  666990238                          0
3  666999616                          0
4  667005177                        374

### Numerical

In [12]:
numerical_columns = ['plc_turnover_gbp', 'plc_turnover_gbp_rcash', 'plc_turnover_gbp_bonus', 'plc_betcount',
    
    'stl_turnover_gbp', 'stl_turnover_gbp_rcash', 'stl_turnover_gbp_bonus', 'stl_ggr_gbp', 'stl_ggr_gbp_rcash', 'stl_ggr_gbp_bonus', 'stl_betcount',
    
    # not in description, columns most probably calculated from other columns
    #'stl_betting_duty', 'stl_licence_fee', 'stl_tax', 'stl_partnerfee',

    'deposit_gbp', 'withdrawal_gbp',
    
    'bonus_costs', 'realcash_costs', 'bonusfunds_costs', 'bonus_costs_accurrency', 'bonusfunds_costs_accurrency'
]

In [13]:
df_numerical = df_data[list(['accountid']) + numerical_columns].groupby('accountid', as_index=False).agg({
    'plc_turnover_gbp': ['min', 'mean', 'median', 'max', 'nunique'],
    'plc_turnover_gbp_rcash': ['min', 'mean', 'median', 'max', 'nunique'],
    'plc_turnover_gbp_bonus': ['min', 'mean', 'median', 'max', 'nunique'],
    'plc_betcount': ['min', 'mean', 'median', 'max', 'nunique'],
    
    'stl_turnover_gbp': ['min', 'mean', 'median', 'max', 'nunique'],
    'stl_turnover_gbp_rcash': ['min', 'mean', 'median', 'max', 'nunique'],
    'stl_turnover_gbp_bonus': ['min', 'mean', 'median', 'max', 'nunique'],
    'stl_ggr_gbp': ['min', 'mean', 'median', 'max', 'nunique'],
    'stl_ggr_gbp_rcash': ['min', 'mean', 'median', 'max', 'nunique'],
    'stl_ggr_gbp_bonus': ['min', 'mean', 'median', 'max', 'nunique'],
    'stl_betcount': ['min', 'mean', 'median', 'max', 'nunique'],

    'deposit_gbp': ['min', 'mean', 'median', 'max', 'nunique'],
    'withdrawal_gbp': ['min', 'mean', 'median', 'max', 'nunique'],
    
    'bonus_costs': ['min', 'mean', 'median', 'max', 'nunique'],
    'realcash_costs': ['min', 'mean', 'median', 'max', 'nunique'],
    'bonusfunds_costs': ['min', 'mean', 'median', 'max', 'nunique'],
    'bonus_costs_accurrency': ['min', 'mean', 'median', 'max', 'nunique'],
    'bonusfunds_costs_accurrency': ['min', 'mean', 'median', 'max', 'nunique']
})

df_numerical.columns = [
    col[0] if col[1] == '' else f'{col[0]}_{col[1]}'
    for col in df_numerical.columns
]

In [14]:
df_numerical[:5]

,accountid,plc_turnover_gbp_min,plc_turnover_gbp_mean,plc_turnover_gbp_median,plc_turnover_gbp_max,plc_turnover_gbp_nunique,plc_turnover_gbp_rcash_min,plc_turnover_gbp_rcash_mean,plc_turnover_gbp_rcash_median,plc_turnover_gbp_rcash_max,...,bonus_costs_accurrency_min,bonus_costs_accurrency_mean,bonus_costs_accurrency_median,bonus_costs_accurrency_max,bonus_costs_accurrency_nunique,bonusfunds_costs_accurrency_min,bonusfunds_costs_accurrency_mean,bonusfunds_costs_accurrency_median,bonusfunds_costs_accurrency_max,bonusfunds_costs_accurrency_nunique
0,666989420,0.0,0.756415,0.50,15.00,43,0.0,0.703585,0.5,6.00,...,0.0,0.052830,0.0,10.0,3,0.0,0.052830,0.0,10.0,3
1,666989923,0.0,23.413187,5.00,426.00,40,0.0,21.800733,0.0,426.00,...,0.0,1.611722,0.0,25.0,6,0.0,1.611722,0.0,25.0,6
2,666990238,0.0,9.396947,5.00,110.00,14,0.0,7.087786,0.0,100.00,...,0.0,2.309160,0.0,17.0,8,0.0,2.309160,0.0,17.0,8
3,666999616,0.0,21.793820,9.50,779.00,42,0.0,21.793820,9.5,779.00,...,0.0,0.000000,0.0,0.0,1,0.0,0.000000,0.0,0.0,1
4,667005177,0.0,42.962111,6.25,425.17,114,0.0,41.885986,5.0,425.17,...,0.0,1.076125,0.0,25.0,7,0.0,1.076125,0.0,25.0,7

### Ohe

In [15]:
columns_to_be_ohed = ['agp_brand', 'reporting_region', 'market', 'reg_prod', 'foundation_category', 'account_tier', 'category', 'activity_channel', 'secondary_product', 'bet_type', 'productgroup']

In [16]:
df_data_ohe = pd.get_dummies(df_data[list(['accountid']) + columns_to_be_ohed], columns=columns_to_be_ohed, sparse=False, drop_first=True)

In [17]:
df_data_ohe[:5]

,accountid,agp_brand_Parimatch UK,reporting_region_United Kingdom,market_Ireland,market_Parimatch UK,reg_prod_Sports,reg_prod_eGaming,foundation_category_Paint,foundation_category_Plaster,account_tier_AVERAGE,...,bet_type_Others,bet_type_RnG,bet_type_Single,productgroup_Casino,productgroup_Live Casino,productgroup_Lottery,productgroup_Overall,productgroup_Sportsbook,productgroup_Virtual Sports,productgroup_eSports
6397,666989420,True,True,False,True,True,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False
53760,666989420,True,True,False,True,True,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
53761,666989420,True,True,False,True,True,False,True,False,False,...,False,False,True,False,False,False,False,True,False,False
137109,666989420,True,True,False,True,True,False,True,False,False,...,False,False,True,False,False,False,False,True,False,False
143199,666989420,True,True,False,True,True,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False

In [18]:
agg_dict = {col: ["min", "max"] for col in df_data_ohe.columns[1:]}

In [19]:
df_data_ohe_grouped = df_data_ohe.groupby('accountid', as_index=False).agg(agg_dict)

df_data_ohe_grouped.columns = [
    col[0] if col[1] == '' else f'{col[0]}_{col[1]}'
    for col in df_data_ohe_grouped.columns
]

### Merging

In [20]:
df_training_set = pd.merge(
    account_age,
    time_to_first_deposit_age,
    how='left',
    on='accountid'
)

In [21]:
df_training_set = pd.merge(
    df_training_set,
    df_data_ohe_grouped,
    how='left',
    on='accountid'
)

In [22]:
df_training_set = pd.merge(
    df_training_set,
    df_numerical,
    how='left',
    on='accountid'
)

In [23]:
df_training_set.sort_values('accountid', inplace=True)

In [24]:
y = df_data[['accountid', 'registration_date', 'is_churned']].groupby('accountid', as_index=False).agg({
    'registration_date': 'first',
    'is_churned': 'max'
}).sort_values('accountid', inplace=False)

In [25]:
df_training_set[:5]

,accountid,registration_date,account_age_in_days,time_to_first_deposit_age,agp_brand_Parimatch UK_min,agp_brand_Parimatch UK_max,reporting_region_United Kingdom_min,reporting_region_United Kingdom_max,market_Ireland_min,market_Ireland_max,...,bonus_costs_accurrency_min,bonus_costs_accurrency_mean,bonus_costs_accurrency_median,bonus_costs_accurrency_max,bonus_costs_accurrency_nunique,bonusfunds_costs_accurrency_min,bonusfunds_costs_accurrency_mean,bonusfunds_costs_accurrency_median,bonusfunds_costs_accurrency_max,bonusfunds_costs_accurrency_nunique
0,666989420,2020-10-03,684,0,True,True,True,True,False,False,...,0.0,0.052830,0.0,10.0,3,0.0,0.052830,0.0,10.0,3
1,666989923,2020-10-03,507,0,True,True,True,True,False,False,...,0.0,1.611722,0.0,25.0,6,0.0,1.611722,0.0,25.0,6
2,666990238,2020-10-03,471,0,True,True,True,True,False,False,...,0.0,2.309160,0.0,17.0,8,0.0,2.309160,0.0,17.0,8
3,666999616,2020-10-08,726,0,True,True,True,True,False,False,...,0.0,0.000000,0.0,0.0,1,0.0,0.000000,0.0,0.0,1
4,667005177,2020-10-10,562,374,True,True,True,True,False,False,...,0.0,1.076125,0.0,25.0,7,0.0,1.076125,0.0,25.0,7

In [26]:
y[:5]

   accountid registration_date  is_churned
0  666989420        2020-10-03           0
1  666989923        2020-10-03           0
2  666990238        2020-10-03           0
3  666999616        2020-10-08           0
4  667005177        2020-10-10           0

In [27]:
df_training = df_training_set[df_training_set['registration_date'] < '2022-01-01'][[i for i in df_training_set.columns if i not in ['accountid', 'registration_date']]]
df_test = df_training_set['2022-01-01' <= df_training_set['registration_date']][[i for i in df_training_set.columns if i not in ['accountid', 'registration_date']]]

In [28]:
df_training.shape, df_test.shape

((1323, 276), (677, 276))

In [29]:
df_training_y = y[y['registration_date'] < '2022-01-01'][[i for i in y.columns if i not in ['accountid', 'registration_date']]]
df_test_y = y['2022-01-01' <= y['registration_date']][[i for i in y.columns if i not in ['accountid', 'registration_date']]]

In [30]:
df_training_y.shape, df_test_y.shape

((1323, 1), (677, 1))

In [31]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, cohen_kappa_score, roc_auc_score, precision_recall_curve, auc

In [32]:
def calculate_metrics(title, y_true, y_pred):
    precision, recall, thresholds = precision_recall_curve(y_true, y_pred)
    pr_auc_trapz = auc(recall, precision)

    print("{:}\n- Accuracy: {:>15.4f}\n- Precision: {:>14.4f}\n- Recall: {:>17.4f}\n- F1 score: {:>15.4f}\n- Cohen-kappa score: {:>6.4f}\n- ROC AuC: {:>16.4f}\n- PR AuC: {:>17.4f}".format(
        title,
        accuracy_score(y_true, y_pred),
        precision_score(y_true, y_pred),
        recall_score(y_true, y_pred),
        f1_score(y_true, y_pred),
        cohen_kappa_score(y_true, y_pred),
        roc_auc_score(y_true, y_pred),
        pr_auc_trapz
    ))

## Decision tree

In [33]:
from sklearn.tree import DecisionTreeClassifier

In [34]:
clf = DecisionTreeClassifier()

In [35]:
clf.fit(df_training, df_training_y['is_churned'])

DecisionTreeClassifier()

In [36]:
df_training_y['prediction'] = clf.predict(df_training)
df_test_y['prediction'] = clf.predict(df_test)

In [37]:
calculate_metrics("Training set:", df_training_y['is_churned'], df_training_y['prediction'])

Training set:
- Accuracy:          1.0000
- Precision:         1.0000
- Recall:            1.0000
- F1 score:          1.0000
- Cohen-kappa score: 1.0000
- ROC AuC:           1.0000
- PR AuC:            1.0000

In [38]:
calculate_metrics("Test set:", df_test_y['is_churned'], df_test_y['prediction'])

Test set:
- Accuracy:          0.3072
- Precision:         1.0000
- Recall:            0.0042
- F1 score:          0.0085
- Cohen-kappa score: 0.0026
- ROC AuC:           0.5021
- PR AuC:            0.8485

## RandomForest

In [39]:
from sklearn.ensemble import RandomForestClassifier

In [40]:
clf = RandomForestClassifier()

In [41]:
clf.fit(df_training, df_training_y['is_churned'])

RandomForestClassifier()

In [42]:
df_training_y['prediction'] = clf.predict(df_training)
df_test_y['prediction'] = clf.predict(df_test)

In [43]:
calculate_metrics("Training set:", df_training_y['is_churned'], df_training_y['prediction'])

Training set:
- Accuracy:          1.0000
- Precision:         1.0000
- Recall:            1.0000
- F1 score:          1.0000
- Cohen-kappa score: 1.0000
- ROC AuC:           1.0000
- PR AuC:            1.0000

In [44]:
calculate_metrics("Test set:", df_test_y['is_churned'], df_test_y['prediction'])

Test set:
- Accuracy:          0.3545
- Precision:         0.8864
- Recall:            0.0828
- F1 score:          0.1515
- Cohen-kappa score: 0.0370
- ROC AuC:           0.5293
- PR AuC:            0.8036

## GradientBoosting

In [45]:
from sklearn.ensemble import GradientBoostingClassifier

In [46]:
clf = GradientBoostingClassifier()

In [47]:
clf.fit(df_training, df_training_y['is_churned'])

GradientBoostingClassifier()

In [48]:
df_training_y['prediction'] = clf.predict(df_training)
df_test_y['prediction'] = clf.predict(df_test)

In [49]:
calculate_metrics("Training set:", df_training_y['is_churned'], df_training_y['prediction'])

Training set:
- Accuracy:          0.9138
- Precision:         0.8729
- Recall:            0.9784
- F1 score:          0.9227
- Cohen-kappa score: 0.8261
- ROC AuC:           0.9104
- PR AuC:            0.9313

In [50]:
calculate_metrics("Test set:", df_test_y['is_churned'], df_test_y['prediction'])

Test set:
- Accuracy:          0.3072
- Precision:         1.0000
- Recall:            0.0042
- F1 score:          0.0085
- Cohen-kappa score: 0.0026
- ROC AuC:           0.5021
- PR AuC:            0.8485