# Senate meeting minutes processor
Last updated: _2026.10.01_

## Configuration

In [1]:
WORK_DIR = "senate_meeting_minutes"
INPUT_URL = "https://www.uni-corvinus.hu/fooldal/egyetemunkrol/szenatus-egyetemi-testuletek/szenatus/"

## URL crawler

In [2]:
import re

import requests

import pandas as pd

from pathlib import Path
from getpass import getpass
from bs4 import BeautifulSoup

from urllib.parse import unquote, urljoin, urlparse

In [3]:
headers = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/151.0.0.0 Safari/537.36"
    )
}

session = requests.Session()
session.headers.update(headers)

protected_page = session.get(INPUT_URL, timeout=30)
protected_soup = BeautifulSoup(protected_page.text, "html.parser")
login_link = protected_soup.find(
    "a",
    href=re.compile(r"wp-login\.php(?:\?|$)"),
)

if (
    protected_page.status_code < 400
    and protected_soup.select_one(".sidebar-nav") is not None
):
    authenticated_page = protected_page
    authenticated_soup = protected_soup
elif login_link is None:
    protected_page.raise_for_status()
    raise RuntimeError(
        f"Could not find .sidebar-nav or a login link at {protected_page.url!r}."
    )
else:
    login_page = session.get(
        urljoin(protected_page.url, login_link["href"]),
        timeout=30,
    )
    login_soup = BeautifulSoup(login_page.text, "html.parser")
    login_form = login_soup.find("form")

    if login_page.status_code >= 400 and login_page.status_code != 401:
        login_page.raise_for_status()
    if login_form is None:
        if login_page.status_code == 401:
            raise RuntimeError(
                f"The SSO login page returned 401 Unauthorized at {login_page.url!r}; "
                "the login flow cannot continue because no login form was provided."
            )
        raise RuntimeError(f"Could not find the login form at {login_page.url!r}.")

    hidden_fields = {
        field["name"]: field.get("value", "")
        for field in login_form.select("input[type=hidden][name]")
    }

    username = input("Corvinus username: ").strip()
    if not username:
        raise ValueError("A Corvinus username is required.")

    password = getpass("Corvinus password: ")
    if not password:
        raise ValueError("A Corvinus password is required.")

    login_data = {
        **hidden_fields,
        "username": username,
        "password": password,
    }
    login_data.setdefault("_eventId", "submit")

    login_action = urljoin(
        login_page.url,
        login_form.get("action") or login_page.url,
    )
    authenticated_page = session.post(
        login_action,
        data=login_data,
        timeout=30,
    )
    authenticated_soup = BeautifulSoup(authenticated_page.text, "html.parser")

    if authenticated_page.status_code == 401 or authenticated_page.url.startswith(
        "https://sso.uni-corvinus.hu/cas/login"
    ):
        error = authenticated_soup.select_one("#msg, .errors, .alert-danger")
        detail = error.get_text(" ", strip=True) if error else "credentials were rejected"
        raise RuntimeError(f"CAS login failed: {detail}")

    authenticated_page.raise_for_status()

Corvinus username:  bzoltan1
Corvinus password:  ··············

In [4]:
output_dir = Path.cwd() / WORK_DIR
output_dir.mkdir(parents=True, exist_ok=True)

sidebar_links = []
seen_sidebar_urls = set()
for link in authenticated_soup.select(".sidebar-nav a[href]"):
    sidebar_url = urljoin(authenticated_page.url, link["href"])
    if sidebar_url in seen_sidebar_urls:
        continue

    seen_sidebar_urls.add(sidebar_url)
    sidebar_label = link.get_text(" ", strip=True)
    if not sidebar_label:
        sidebar_label = link.get("aria-label") or link.get("title") or sidebar_url

    sidebar_links.append(
        {
            "label": sidebar_label,
            "url": sidebar_url,
        }
    )

if not sidebar_links:
    raise RuntimeError(
        "No links were found in .sidebar-nav after login; the page may have changed "
        "or the account may not have access."
    )

pd.DataFrame(sidebar_links, columns=["label", "url"]).to_csv(
    output_dir / "senate_sidebar_links.csv",
    index=False,
    encoding="utf-8-sig",
)

In [5]:
pdf_records = []
not_found_links = []
unauthorized_links = []
connection_error_links = []
seen_pdf_urls = set()
for page_index, sidebar_link in enumerate(sidebar_links, start=1):
    print(
        f"Reading {page_index}/{len(sidebar_links)}: "
        f"{sidebar_link['label']}"
    )
    try:
        section_page = session.get(sidebar_link["url"], timeout=30)
    except requests.exceptions.ConnectionError as error:
        print(f"  Connection error: {sidebar_link['url']} ({error})")
        connection_error_links.append(
            {
                "type": "sidebar_page",
                "label": sidebar_link["label"],
                "url": sidebar_link["url"],
                "error": str(error),
            }
        )
        continue

    if section_page.status_code == 401:
        print(f"  401 Unauthorized: {section_page.url}")
        unauthorized_links.append(
            {
                "type": "sidebar_page",
                "label": sidebar_link["label"],
                "url": sidebar_link["url"],
                "error": "Unauthorized",
            }
        )
        continue

    if section_page.status_code == 404:
        print(f"  404 Not Found: {section_page.url}")
        not_found_links.append(
            {
                "type": "sidebar_page",
                "label": sidebar_link["label"],
                "url": sidebar_link["url"],
            }
        )
        continue

    section_page.raise_for_status()
    section_soup = BeautifulSoup(section_page.text, "html.parser")
    main = section_soup.find("main")

    if main is None:
        print(f"  No <main> tag found at {section_page.url}")
        continue

    for pdf_link in main.select("a[href]"):
        pdf_url = urljoin(section_page.url, pdf_link["href"])
        if not urlparse(pdf_url).path.lower().endswith(".pdf"):
            continue
        if pdf_url in seen_pdf_urls:
            continue

        seen_pdf_urls.add(pdf_url)
        pdf_label = pdf_link.get_text(" ", strip=True)
        if not pdf_label:
            pdf_label = pdf_link.get("aria-label") or pdf_link.get("title") or pdf_url

        pdf_records.append(
            {
                "sidebar_label": sidebar_link["label"],
                "sidebar_url": sidebar_link["url"],
                "pdf_label": pdf_label,
                "pdf_url": pdf_url,
                "status": "pending",
                "error": "",
            }
        )

if (
    not pdf_records
    and not not_found_links
    and not unauthorized_links
    and not connection_error_links
):
    raise RuntimeError(
        "No PDF links were found in the <main> tag of the sidebar pages; "
        "the page structure or account access may have changed."
    )

Reading 1/19: Szenátus
Reading 2/19: A Szenátus tagjai
Reading 3/19: 2026/2027
Reading 4/19: 2025/2026
Reading 5/19: 2024/2025
Reading 6/19: 2023/2024
Reading 7/19: 2022/2023
Reading 8/19: 2021/2022
Reading 9/19: 2020/2021
Reading 10/19: 2019/2020
Reading 11/19: 2018/2019
Reading 12/19: 2017/2018
Reading 13/19: 2016/2017
Reading 14/19: 2015/2016
Reading 15/19: 2014/2015
Reading 16/19: 2013/2014
Reading 17/19: 2012/2013
Reading 18/19: 2011/2012
Reading 19/19: 2010/2011

In [6]:
pdf_records[:5]

[{'sidebar_label': 'Szenátus',
  'sidebar_url': 'https://www.uni-corvinus.hu/fooldal/egyetemunkrol/szenatus-egyetemi-testuletek/szenatus/',
  'pdf_label': 'Adatkezelési tájékoztató',
  'pdf_url': 'https://www.uni-corvinus.hu/contents/uploads/2024/05/AT_Szenátus_240515.bc3.pdf',
  'status': 'pending',
  'error': ''},
 {'sidebar_label': '2026/2027',
  'sidebar_url': 'https://www.uni-corvinus.hu/fooldal/egyetemunkrol/szenatus-egyetemi-testuletek/szenatus/2026-2027/',
  'pdf_label': 'Írásbeli szavazás elrendelése',
  'pdf_url': 'https://www.uni-corvinus.hu/downloads/di0f.o8kflc/bce-sz-20260928-irasbeli-szavazas-elrendelese-sgd.pdf',
  'status': 'pending',
  'error': ''},
 {'sidebar_label': '2026/2027',
  'sidebar_url': 'https://www.uni-corvinus.hu/fooldal/egyetemunkrol/szenatus-egyetemi-testuletek/szenatus/2026-2027/',
  'pdf_label': 'Meghívó',
  'pdf_url': 'https://www.uni-corvinus.hu/downloads/dgpo.ok9t7o/senate-invitation-260922-sgd.pdf',
  'status': 'pending',
  'error': ''},
 {'sidebar_label': '2026/2027',
  'sidebar_url': 'https://www.uni-corvinus.hu/fooldal/egyetemunkrol/szenatus-egyetemi-testuletek/szenatus/2026-2027/',
  'pdf_label': '1. melléklet',
  'pdf_url': 'https://www.uni-corvinus.hu/downloads/dgqg.m0loyt/1-local-resilience.pdf',
  'status': 'pending',
  'error': ''},
 {'sidebar_label': '2026/2027',
  'sidebar_url': 'https://www.uni-corvinus.hu/fooldal/egyetemunkrol/szenatus-egyetemi-testuletek/szenatus/2026-2027/',
  'pdf_label': '2. melléklet',
  'pdf_url': 'https://www.uni-corvinus.hu/downloads/dgqh.16dl0cd/2-nedimarc-neuro-and-digital-marketing.pdf',
  'status': 'pending',
  'error': ''}]

In [7]:
used_filenames = set()
for index, record in enumerate(pdf_records, start=1):
    pdf_url = record["pdf_url"]
    filename = Path(unquote(urlparse(pdf_url).path)).name
    filename = re.sub(r'[<>:"/\\|?*\x00-\x1f]', "_", filename)
    if not filename:
        filename = f"senate_{index:04d}.pdf"

    original_filename = filename
    duplicate_number = 2
    while filename in used_filenames:
        path = Path(original_filename)
        filename = f"{path.stem}_{duplicate_number}{path.suffix}"
        duplicate_number += 1
    used_filenames.add(filename)
    record["filename"] = filename

    destination = output_dir / filename
    partial_destination = destination.with_suffix(destination.suffix + ".part")
    print(f"Downloading {index}/{len(pdf_records)}: {filename}")

    try:
        with session.get(pdf_url, stream=True, timeout=60) as pdf_response:
            if pdf_response.status_code == 401:
                record["status"] = "401"
                record["error"] = "Unauthorized"
                unauthorized_links.append(
                    {
                        "type": "pdf",
                        "label": record["pdf_label"],
                        "url": pdf_url,
                        "error": "Unauthorized",
                    }
                )
                print(f"  401 Unauthorized: {pdf_url}")
                continue

            if pdf_response.status_code == 404:
                record["status"] = "404"
                record["error"] = "Not Found"
                not_found_links.append(
                    {
                        "type": "pdf",
                        "label": record["pdf_label"],
                        "url": pdf_url,
                    }
                )
                print(f"  404 Not Found: {pdf_url}")
                continue

            pdf_response.raise_for_status()
            first_chunk = next(pdf_response.iter_content(chunk_size=8192), b"")
            if not first_chunk.startswith(b"%PDF"):
                raise RuntimeError(
                    f"The response for {pdf_url} was not a PDF; "
                    "the authenticated session may have expired."
                )

            with partial_destination.open("wb") as output_file:
                output_file.write(first_chunk)
                for chunk in pdf_response.iter_content(chunk_size=8192):
                    if chunk:
                        output_file.write(chunk)

        partial_destination.replace(destination)
        record["status"] = "downloaded"
    except requests.exceptions.ConnectionError as error:
        record["status"] = "connection_error"
        record["error"] = str(error)
        connection_error_links.append(
            {
                "type": "pdf",
                "label": record["pdf_label"],
                "url": pdf_url,
                "error": str(error),
            }
        )
        print(f"  Connection error: {pdf_url} ({error})")
    finally:
        try:
            partial_destination.unlink()
        except FileNotFoundError:
            pass

Downloading 1/454: AT_Szenátus_240515.bc3.pdf
Downloading 2/454: bce-sz-20260928-irasbeli-szavazas-elrendelese-sgd.pdf
Downloading 3/454: senate-invitation-260922-sgd.pdf
Downloading 4/454: 1-local-resilience.pdf
Downloading 5/454: 2-nedimarc-neuro-and-digital-marketing.pdf
Downloading 6/454: 3-transport-studies.pdf
Downloading 7/454: 4-social-and-environmental-impact-research.pdf
Downloading 8/454: szenatus-munkaterve-2025-2026-frissitett-1.pdf
Downloading 9/454: senate-invitation-260807-sgd.pdf
Downloading 10/454: hatarozatok-260807-veg.pdf
Downloading 11/454: senate-invitation-260713-sgd.pdf
Downloading 12/454: hatarozatok-260713-final.pdf
Downloading 13/454: palyazati-felhivas-kekva.pdf
Downloading 14/454: senate-invitation-260616-sgd.pdf
Downloading 15/454: hatarozatok-260616.pdf
Downloading 16/454: 2a-1-melleklet.pdf
Downloading 17/454: 4-amendment-of-the-statutes-proposal-laczkovich-anna.pdf
Downloading 18/454: taj2-inf2-melleklet.pdf
Downloading 19/454: kozvetitoi-es-fegyelmi-eljarasok-szabalyzata-hu.pdf
Downloading 20/454: taj3-inf3-nyilatkozat-statement.pdf
Downloading 21/454: cat2026-kerdoiv-en.pdf
Downloading 22/454: bce-sz-260603-irasbeli-szavazas-elrendelese-hu-sbv.pdf
Downloading 23/454: jegyzokonyv-260603.pdf
Downloading 24/454: doktori-szabalyzat-20260527-en-lo.pdf
Downloading 25/454: bce-sz-260526-irasbeli-szavazas-elrendelese-hu-ai.pdf
Downloading 26/454: bce-sz-260526-irasbeli-szavazasi-eljaras-megszuntetese-hu-ai.pdf
Downloading 27/454: senate-invitation-260519-sgd.pdf
Downloading 28/454: hatarozatok-260519-final.pdf
Downloading 29/454: 1-1-beszamolo-2025.pdf
Downloading 30/454: 1-2-bce-konyvvizsgaloi-jelentes-2025-hu.pdf
Downloading 31/454: taj1-melleklethun-proposed-charter-of-academic-autonomy-hu.pdf
Downloading 32/454: meghivo-260421-ai.pdf
Downloading 33/454: hatarozatok-260421.pdf
Downloading 34/454: 1-melleklet-1.pdf
Downloading 35/454: 2-melleklet.pdf
Downloading 36/454: taj-inf-1-melleklet-annex.pdf
Downloading 37/454: bce-sz-260402-irasbeli-szavazas-elrendelese-hu-ai.pdf
Downloading 38/454: jegyzokonyv-260409.pdf
Downloading 39/454: 1-hok-alapszabaly-modositas.pdf
Downloading 40/454: 1-melleklet.pdf
Downloading 41/454: bce-sz-260325-irasbeli-szavazas-elrendelese-hu-ai.pdf
Downloading 42/454: jegyzokonyv-260330.pdf
Downloading 43/454: meghivo-260317-ai.pdf
Downloading 44/454: hatarozatok-260317.pdf
Downloading 45/454: sz-jegyzokonyv-250317.pdf
Downloading 46/454: taj-1-eb-beszamolo-2025.pdf
Downloading 47/454: meghivo-260303-ai.pdf
Downloading 48/454: hatarozatok-260303.pdf
Downloading 49/454: sz-jegyzokonyv-260303-ai.pdf
Downloading 50/454: 1-1-modositott-szmr.pdf
Downloading 51/454: 1-2-organogram.pdf
Downloading 52/454: taj-inf-2-aem-acm-1.pdf
Downloading 53/454: taj-inf-3-melleklet-annex.pdf
Downloading 54/454: meghivo-260127-ai.pdf
Downloading 55/454: hatarozatok-260127.pdf
Downloading 56/454: sz-jegyzokonyv-260127.pdf
Downloading 57/454: bce-sz-260106-irasbeli-szavazas-elrendelese-hu-bvs.pdf
Downloading 58/454: jegyzokonyv-260109-ai.pdf
Downloading 59/454: bce-sz-251215-irasbeli-szavazas-elrendelese-hu-ai.pdf
Downloading 60/454: jegyzokonyv-251218-ai.pdf
Downloading 61/454: meghivo-251211-ai-1.pdf
Downloading 62/454: hatarozatok-251211.pdf
Downloading 63/454: sz-jegyzokonyv-251211-c.pdf
Downloading 64/454: 1-budget-2026.pdf
Downloading 65/454: meghivo-251118-ai.pdf
Downloading 66/454: hatarozatok-251118.pdf
Downloading 67/454: sz-jegyzokonyv-251118-c.pdf
Downloading 68/454: 1-1-seed-brief-2025november.pdf
Downloading 69/454: 1-1-szmr.pdf
Downloading 70/454: tajekoztatas-3-1-melleklet-mi-vb-rendelkezes.pdf
Downloading 71/454: 12-2025-vb-rendelkezes-mi-keretszabalyozas-00.pdf
Downloading 72/454: information-5-annex.pdf
Downloading 73/454: meghivo-251014-ai.pdf
Downloading 74/454: hatarozatok-251014.pdf
Downloading 75/454: jegyzokonyv-nyers-251014.pdf
Downloading 76/454: szenatus-munkaterve-2025-2026.pdf
Downloading 77/454: meghivo-250916-ai-ea.pdf
Downloading 78/454: hatarozatok-250916.pdf
Downloading 79/454: sz-jegyzokonyv-250916-ai.pdf
Downloading 80/454: 3-cte-2.0-koncepcio.pdf
Downloading 81/454: bce-sz-250708-irasbeli-szavazas-elrendelese-hu-ai.pdf
Downloading 82/454: jegyzokonyv-250714-alairt.pdf
Downloading 83/454: 1-intezmenyfejlesztesi-terv-modositas.pdf
Downloading 84/454: meghivo-250624-ai.pdf
Downloading 85/454: hatarozatok-250624.pdf
Downloading 86/454: jegyzokonyv-nyers-valtozat.pdf
Downloading 87/454: 1-intezmenyfejlesztesi-terv-hu-20250617.pdf
Downloading 88/454: 2-melleklet_2.pdf
Downloading 89/454: 3a-melleklet.pdf
Downloading 90/454: 3b-melleklet.pdf
Downloading 91/454: 3c-melleklet.pdf
Downloading 92/454: 3d-melleklet.pdf
Downloading 93/454: 3e-melleklet.pdf
Downloading 94/454: 3f-melleklet.pdf
Downloading 95/454: 3g-melleklet.pdf
Downloading 96/454: 3h-melleklet.pdf
Downloading 97/454: bce-sz-250528-irasbeli-szavazas-elrendelese-hu-alairt.pdf
Downloading 98/454: jegyzokonyv-250602.pdf
Downloading 99/454: meghivo-250520-alairt.pdf
Downloading 100/454: hatarozatok-250520.pdf
Downloading 101/454: sz-jegyzokonyv-250520-ai.pdf
Downloading 102/454: 1-melleklet-1-eves-beszamolo-2024.pdf
Downloading 103/454: 1-melleklet-2-konyvvizsgaloi-jelentes-2024.pdf
Downloading 104/454: meghivo-250415-ai.pdf
Downloading 105/454: hatarozatok-250415.pdf
Downloading 106/454: jegyzokonyv-20250415-sgd.pdf
Downloading 107/454: meghivo-250318-sgd.pdf
Downloading 108/454: hatarozatok-250318-alairt.pdf
Downloading 109/454: sz-jegyzokonyv-250318-ai.pdf
Downloading 110/454: meghivo-250306-alairt-rektor.pdf
Downloading 111/454: hatarozatok-250306-alairt.pdf
Downloading 112/454: meghivo-250218-alairt.pdf
Downloading 113/454: hatarozatok-250218-alairt.pdf
Downloading 114/454: minutes-250218.pdf
Downloading 115/454: meghivo-241210.pdf
Downloading 116/454: hatarozatok-241210-alairt.pdf
Downloading 117/454: sz-jegyzokonyv-241210-sgd.pdf
Downloading 118/454: beszamolo-2024.q1-q3-szenatus-hun.pdf
Downloading 119/454: meghivo-241112-sign.pdf
Downloading 120/454: hatarozatok-241112.pdf
Downloading 121/454: sz-jegyzokonyv-241112-sgd.pdf
Downloading 122/454: bce-sz-241018-irasbeli-szavazas-elrendelese-hu.pdf
Downloading 123/454: jegyzokonyv-241024.pdf
Downloading 124/454: invitation.pdf
Downloading 125/454: hatarozatok-241008-en-alairt.pdf
Downloading 126/454: sz-jegyzokonyv-241008.pdf
Downloading 127/454: oop-clarified-2.pdf
Downloading 128/454: 2a-admissions-regulation-amended.pdf
Downloading 129/454: bce-sz-240924-irasbeli-szavazas-elrendelese-hu.pdf
Downloading 130/454: jegyzokonyv-240924.pdf
Downloading 131/454: Szenatus_munkaterve_2023_2024_I_felev.101.pdf
Downloading 132/454: Szenatus_munkaterve_2023_2024_II_felev.90b.pdf
Downloading 133/454: bce-sz-240801-irasbeli-szavazas-elrendelese-hu-signed.pdf
Downloading 134/454: jegyzokonyv-240822.pdf
Downloading 135/454: meghivo-240716-alairt.pdf
Downloading 136/454: hatarozatok-240716-alairt.pdf
Downloading 137/454: sz-jegyzokonyv-240716-sgn.pdf
Downloading 138/454: 1-demonstratori-szabalyzat.pdf
Downloading 139/454: 4-qtem-application-corvinus-2024.pdf
Downloading 140/454: ift-funkc-strat-elorehaladas-2024-1-reszletes.pdf
Downloading 141/454: beszamolo.pdf
Downloading 142/454: meghivo_240611_ALÁÍRT.4cb.pdf
Downloading 143/454: hatarozatok-240611.pdf
Downloading 144/454: sz-jegyzokonyv-240611.pdf
Downloading 145/454: 1a_HKR_1_Felveteli_szabalyzat.083.pdf
Downloading 146/454: 1c_HKR_3_TVSZ.382.pdf
Downloading 147/454: 1d_SR_4_HTJSZ.c55.pdf
Downloading 148/454: 1e_HKR_5_Fogyatekosugyi_szabalyzat.86a.pdf
Downloading 149/454: 1f_HKR_8_Doktori_szabalyzat.b79.pdf
Downloading 150/454: meghivo_240522_ALÁÍRT.9c4.pdf
Downloading 151/454: SZ_jegyzokonyv_240522.da9.pdf
Downloading 152/454: meghivo_240507_alairt.cc1.pdf
Downloading 153/454: hatarozatok_240507_alairt.003.pdf
Downloading 154/454: SZ_jegyzokonyv_240507.b0a.pdf
Downloading 155/454: 1_Szenatus_ugyrendje_mod_tervezet.0d6.pdf
Downloading 156/454: BCE_SZ_240430_irasbeli_szavazas_elrendelese_alairt.58a.pdf
Downloading 157/454: jegyzokonyv_240508.1dc.pdf
Downloading 158/454: 3_1_melleklet_Corvinus_Eves_jelentes_2023.ee4.pdf
Downloading 159/454: 3_2_melleklet_Vezetoi_prezentacio_2023.570.pdf
Downloading 160/454: 3_3_melleklet_BCE_Eves_beszamolo_es_kozhasznusagi_melleklet_2023.c54.pdf
Downloading 161/454: 3_4_melleklet_BCE_konyvvizsgaloi_jelentes_2023_alairt.706.pdf
Downloading 162/454: 3_5_Kozhasznu_FB_jelentes_alairt_2023.70c.pdf
Downloading 163/454: meghivo_240409_alairt.6bd.pdf
Downloading 164/454: hatarozatok_240409_alairt.0bf.pdf
Downloading 165/454: sz-jegyzokonyv-240409-alairt.pdf
Downloading 166/454: meghivo_240312_ALÁÍRT.967.pdf
Downloading 167/454: hatarozatok_240312_alairt.e9b.pdf
Downloading 168/454: SZ_jegyzokonyv_240312.d1e.pdf
Downloading 169/454: meghivo_240229_alairt.3aa.pdf
Downloading 170/454: hatarozatok_240229_alairt.341.pdf
Downloading 171/454: SZ_jegyzokonyv_240229.40d.pdf
Downloading 172/454: 1_IFT_eloterjesztes.a5e.pdf
Downloading 173/454: 1_BCE_IFT_2024-2027.121.pdf
Downloading 174/454: 1_IFT_2024_2027_Indikatorok.c98.pdf
Downloading 175/454: meghivo_240213_alairt.678.pdf
Downloading 176/454: hatarozatok_240213.846.pdf
Downloading 177/454: SZ_jegyzokonyv_240213.0a4.pdf
Downloading 178/454: meghivo_240116_ALÁÍRT.233.pdf
Downloading 179/454: hatarozatok_240116.01f.pdf
Downloading 180/454: SZ_jegyzokonyv_240116.203.pdf
Downloading 181/454: IFT_2024-2027.b09.pdf
Downloading 182/454: 1_Oktatasi_strategia_2024_2027.025.pdf
Downloading 183/454: 1_Teaching_Strategy_2024_2027.28c.pdf
Downloading 184/454: 2_Kutatasi_strategia_2024_2027.be7.pdf
Downloading 185/454: 2_Research_Strategy_2024_2027.adf.pdf
Downloading 186/454: 3_Tehetsegmenedzsment_koncepcio.95c.pdf
Downloading 187/454: Tajekoztatas_Tarsadalomtudomanyi_alapszakok.d92.pdf
Downloading 188/454: Tajekoztatas_Mesterkepzesi_portfolio_fejlesztese.b01.pdf
Downloading 189/454: jegyzokonyv_231220.f4f.pdf
Downloading 190/454: meghivo_231205_alairt.555.pdf
Downloading 191/454: hatarozatok_231205.804.pdf
Downloading 192/454: SZ_jegyzokonyv_231205.e0f.pdf
Downloading 193/454: 1_SZMR_modositas_1_fuggelek.678.pdf
Downloading 194/454: 3_DOK_Alapszabaly_modositas_tervezet.e42.pdf
Downloading 195/454: Meghívó_2023_11_14_ALÁÍRT.7b2.pdf
Downloading 196/454: hatarozatok_231114_alairt.f5c.pdf
Downloading 197/454: SZ_jegyzokonyv_231114.5c9.pdf
Downloading 198/454: meghivo_231107_ikt_jav_ALÁÍRT.b61.pdf
Downloading 199/454: hatarozatok_231107_alairt.e85.pdf
Downloading 200/454: SZ_jegyzokonyv_231107.9c0.pdf
Downloading 201/454: 1_HKR_1_felveteli_szabalyzat_szabalyzattervezet.195.pdf
Downloading 202/454: 2_HKR_9_kulfoldi_reszkepzesi_szabalyzat_szabalyzattervezet.1a8.pdf
Downloading 203/454: BCE_SZ_231013_irasbeli_szavazas_elrendelese.0d4.pdf
Downloading 204/454: jegyzokonyv_231018_alairt.60a.pdf
Downloading 205/454: meghivo_231010_alairt.156.pdf
Downloading 206/454: hatarozatok_231010.438.pdf
Downloading 207/454: SZ_jegyzokonyv_231010_alairt.214.pdf
Downloading 208/454: 1_HTJSZ_szabalyzat.c24.pdf
Downloading 209/454: Szenatus_munkaterve_2023_2024_I_felev.23a.pdf
Downloading 210/454: meghivo_230912_alairt.907.pdf
Downloading 211/454: hatarozatok_230912.88d.pdf
Downloading 212/454: SZ_jegyzokonyv_230912.a16.pdf
Downloading 213/454: Beszámoló_2023_Q1-Q2_Szenatus_CAT_korr.c53.pdf
Downloading 214/454: meghivo_230711_modositott_alairt.0ef.pdf
Downloading 215/454: hatarozatok_230711.775.pdf
Downloading 216/454: SZ_jegyzokonyv_230711.564.pdf
Downloading 217/454: 1a_HKR_2_Jogorvoslati szabalyzat_tervezet.0bb.pdf
Downloading 218/454: 1b_HKR_3_TVSZ_szabalyzat_tervezet.685.pdf
Downloading 219/454: 1c_HKR_4_HTJSZ_szabalyzat_tervezet.bf2.pdf
Downloading 220/454: 1d_HKR_5_Fogyatékosügyi szabályzat_szabalyzat_tervezet.9d9.pdf
Downloading 221/454: 1e_HKR_6_HFKSZ_szabalyzat_tervezet.113.pdf
Downloading 222/454: 1f_HKR_8_Doktori szabalyzat_tervezet.3d5.pdf
Downloading 223/454: 5_MAB_akkreditacio_intezmenyi_onertekeles_tajekoztatas.a48.pdf
Downloading 224/454: meghivo_230509_alairt.bd2.pdf
Downloading 225/454: hatarozatok_230509.01f.pdf
Downloading 226/454: SZ_jegyzokonyv_230509.5cf.pdf
Downloading 227/454: 2_2.sz.melleklet_Vezetoi_prezentacio.5a8.pdf
Downloading 228/454: 2_3.sz.melleklet_BCE_Eves_beszamolo_es_kozhasznusagi_2022.47b.pdf
Downloading 229/454: 2_5.sz.melleklet_Kozhasznu_FB_jelentes.794.pdf
Downloading 230/454: 2_BCE_könyvvizsgálói jelentés 2022_előzetes_aláírt.393.pdf
Downloading 231/454: 3_Szenátus_Stratégiai keretek.c6b.pdf
Downloading 232/454: 4_SZMR_modositas_szovegszeru_javaslat.f04.pdf
Downloading 233/454: Beszámoló_2023_Q1.5fd.pdf
Downloading 234/454: hatarozatok_230404.753.pdf
Downloading 235/454: SZ_jegyzokonyv_230404.da4.pdf
Downloading 236/454: 1_Professzori_Testulet_beszamolo_2022.c44.pdf
Downloading 237/454: 2_Kutatási, publikációs és nemzetközi akadémiai pályázati beszámoló_melléklet.c57.pdf
Downloading 238/454: 4_DSZ_modositas.cc7.pdf
Downloading 239/454: SZ_jegyzokonyv_230207.470.pdf
Downloading 240/454: 1_IFT_Előrehaladási jelentés 2022_Részletes jelentés.689.pdf
Downloading 241/454: 3_HOK_Alapszabaly_modositas.988.pdf
Downloading 242/454: Szenatus_munkaterve.637.pdf
Downloading 243/454: BCE_SZ_230106_irasbeli_szavazas_elrendelese_alairt.c3c.pdf
Downloading 244/454: jegyzokonyv_230112.b12.pdf
Downloading 245/454: meghivo_221213_alairt.470.pdf
Downloading 246/454: hatarozatok_221213.49d.pdf
Downloading 247/454: SZ_jegyzokonyv_221117.d2e.pdf
Downloading 248/454: Beszámoló_2022_Q3_SZENÁTUS.cea.pdf
Downloading 249/454: SZ_jegyzokonyv_221011.af5.pdf
Downloading 250/454: 2_HKR_4_HTJSZ_2sz_melleklet_onkoltsegi_dijak.b75.pdf
Downloading 251/454: 3_AEB_AAT_tag.e5b.pdf
Downloading 252/454: SZ_jegyzokonyv_220930.b91.pdf
Downloading 253/454: SZ_jegyzokonyv_220913.d43.pdf
Downloading 254/454: 2_SZMR__szabályzattervezet.1fb.pdf
Downloading 255/454: 2_SZMR_2_melleklet_Szellemitulajdon-védelmi és kezelési szabályzat_tervezet.36b.pdf
Downloading 256/454: 4_AEB_AAT_tag.538.pdf
Downloading 257/454: Beszámoló_2022_Q2_Szenátus.b53.pdf
Downloading 258/454: 1_Doktori_szabalyzat_modositasa.0ed.pdf
Downloading 259/454: SZ_jegyzokonyv_220621.29b.pdf
Downloading 260/454: 3_SZMR.eaf.pdf
Downloading 261/454: 8_IFT_elorehaladasi_jelentes_2022_elso_felev.0a7.pdf
Downloading 262/454: 9_HOK_Alapszabaly.156.pdf
Downloading 263/454: Beszámoló_2022_Q1.70f.pdf
Downloading 264/454: SZ_jegyzokonyv_220510.99a.pdf
Downloading 265/454: 1a_prezentacio.f21.pdf
Downloading 266/454: 1b_2021.evi_beszamolo_es_kozhasznusagi_jelentes.a84.pdf
Downloading 267/454: 1c_konyvvizsgaloi_jelentes.da8.pdf
Downloading 268/454: 1d_Kozhasznusagi_beszamolo_2021.9ba.pdf
Downloading 269/454: SZ_jegyzokonyv_220419.9dc.pdf
Downloading 270/454: 2_Jegyzokonyvi_kivonat.30a.pdf
Downloading 271/454: SZ_jegyzokonyv_220316.b06.pdf
  404 Not Found: https://www.uni-corvinus.hu/contents/uploads/2022/04/SZ_jegyzokonyv_220316.b06.pdf
Downloading 272/454: SZ_jegyzokonyv_220308.376.pdf
Downloading 273/454: 1_CDI_dekan.a34.pdf
Downloading 274/454: 5_GEP.055.pdf
Downloading 275/454: hatarozatok_220208.621.pdf
Downloading 276/454: SZ_jegyzokonyv_220208.3dd.pdf
Downloading 277/454: 1_IFT_elorehaladasi_jelentes.fd5.pdf
Downloading 278/454: 3_eseti_bizottsag_vitaanyag.903.pdf
Downloading 279/454: SZ_jegyzokonyv_220111.f66.pdf
Downloading 280/454: 1a_Domotor.275.pdf
Downloading 281/454: 1b_Fodor.3c6.pdf
Downloading 282/454: 1c_Horvath.2c0.pdf
Downloading 283/454: 1d_Illes.cde.pdf
Downloading 284/454: 1e_Mitev.6f3.pdf
Downloading 285/454: 1f_Nagy.766.pdf
Downloading 286/454: 1g_Valentinyi.7ee.pdf
Downloading 287/454: hatarozatok_211214.7c8.pdf
Downloading 288/454: hatarozatok_211130.f33.pdf
Downloading 289/454: 2a_Aczel_Petra.3f5.pdf
Downloading 290/454: 2b_Keszey_Tamara.53b.pdf
Downloading 291/454: 2c_Vas_Reka.7ef.pdf
Downloading 292/454: hatarozatok_211019.be8.pdf
Downloading 293/454: hatarozatok_210921.361.pdf
Downloading 294/454: Corvinus_EQUIS_SAR_2021.fb3.pdf
Downloading 295/454: Corvinus_EQUIS_SAR_2021_Appendix.d09.pdf
Downloading 296/454: hatarozatok_210622.08e.pdf
  404 Not Found: https://www.uni-corvinus.hu/contents/uploads/2021/07/hatarozatok_210622.08e.pdf
Downloading 297/454: 1_EB_IFT.61c.pdf
  404 Not Found: https://www.uni-corvinus.hu/contents/uploads/2021/06/1_EB_IFT.61c.pdf
Downloading 298/454: 2_SZMR.af8.pdf
  404 Not Found: https://www.uni-corvinus.hu/contents/uploads/2021/06/2_SZMR.af8.pdf
Downloading 299/454: hatarozatok_210518.12c.pdf
  404 Not Found: https://www.uni-corvinus.hu/contents/uploads/2021/06/hatarozatok_210518.12c.pdf
Downloading 300/454: 4_1_beszamolo.974.pdf
  404 Not Found: https://www.uni-corvinus.hu/contents/uploads/2021/05/4_1_beszamolo.974.pdf
Downloading 301/454: 4_2_konyvvizsgaloi_jelentes.ee8.pdf
  404 Not Found: https://www.uni-corvinus.hu/contents/uploads/2021/05/4_2_konyvvizsgaloi_jelentes.ee8.pdf
Downloading 302/454: 4_3_KFB_jelentés.730.pdf
  404 Not Found: https://www.uni-corvinus.hu/contents/uploads/2021/05/4_3_KFB_jelent%C3%A9s.730.pdf
Downloading 303/454: bce-ift-2021-2024-210323.89f.pdf
Downloading 304/454: bce-ift-2021-2024-0311.3e7.pdf
Downloading 305/454: meghivo-20210223.5a1.pdf
Downloading 306/454: hatarozatok-210223.412.pdf
Downloading 307/454: hatarozatok-210126.9ef.pdf
Downloading 308/454: 1-szmr-modositas.7b5.pdf
Downloading 309/454: 2-htjsz-modositas.590.pdf
Downloading 310/454: 10-hok-asz.909.pdf
Downloading 311/454: 10-1sz-melleklet.b28.pdf
Downloading 312/454: hatarozatok-201215.c0c.pdf
Downloading 313/454: hatarozatok-201103.4ab.pdf
Downloading 314/454: 1-szmr.74e.pdf
Downloading 315/454: 9-hok-asz.99e.pdf
Downloading 316/454: hatarozatok-200922.1b4.pdf
Downloading 317/454: 2-szmr.109.pdf
Downloading 318/454: hatarozatok-200724.034.pdf
Downloading 319/454: 7-hok-alapszabaly-modositasa.d47.pdf
Downloading 320/454: 8c-8f-napirendi-pontokhoz-tartozo-melleklet.662.pdf
Downloading 321/454: bce-kozhasznu-fb-jelentes-2020.e05.pdf
Downloading 322/454: 6a-elek-peter-edoc.21c.pdf
Downloading 323/454: jegyzokonyv-200512.3b3.pdf
Downloading 324/454: 2-1sz-melleklet-koncepcio-utemterv.ca2.pdf
Downloading 325/454: 2-2sz-melleklet-foig-korlevel.d57.pdf
Downloading 326/454: 2-3sz-melleklet-torzstagi-allomany.340.pdf
Downloading 327/454: 3-hok-asz.5d7.pdf
Downloading 328/454: hatarozatok-191210.0d6.pdf
Downloading 329/454: 1-szakszervezeti-javaslat.c8a.pdf
Downloading 330/454: 4-doktori-szabalyzat-velemenyezese.261.pdf
Downloading 331/454: 5-felveteli-szab.5a9.pdf
Downloading 332/454: 7c-edoc-palyazatok-velemenyezes-tk.d85.pdf
Downloading 333/454: 7cd-vigvari-gabor-edoc.356.pdf
Downloading 334/454: feher-peter-program.3f9.pdf
Downloading 335/454: 2a-hok-alapszabaly-modositas.475.pdf
Downloading 336/454: hatarozatok-190604.59e.pdf
Downloading 337/454: 2-tvsz-modositas.498.pdf
Downloading 338/454: 3a-htjsz-foszoveg.9ee.pdf
Downloading 339/454: 3b-htjsz-1b-melleklet-modositas.931.pdf
Downloading 340/454: 3c-kollegiumi-szmr-modositas.adf.pdf
Downloading 341/454: 6-dok.e4e.pdf
Downloading 342/454: 7-halvel-modositas.bbd.pdf
Downloading 343/454: 8-kt-szmr-mod.152.pdf
Downloading 344/454: 1-beszamolo.5c5.pdf
Downloading 345/454: 2a-koltsegvetes.e9a.pdf
Downloading 346/454: 2b-vgt-modositott.84f.pdf
Downloading 347/454: 2b-fk-modositott.e69.pdf
Downloading 348/454: 6-dsz-modositas.23f.pdf
Downloading 349/454: 7-fsz.f3a.pdf
Downloading 350/454: 8-htjsz.a0b.pdf
Downloading 351/454: 9-tvsz.ed6.pdf
Downloading 352/454: 10-felveteli-szabalyzat.419.pdf
Downloading 353/454: 15-asz-modositas.1b2.pdf
Downloading 354/454: 16-dok-alapszabaly.603.pdf
Downloading 355/454: hatarozatok-190301.0d4.pdf
Downloading 356/454: 1-2018-evi-kincstari-beszamolo.3bb.pdf
Downloading 357/454: 1-2018-evi-kincstari-beszamolo-aktualis.4cf.pdf
Downloading 358/454: hatarozatok-190205.4fd.pdf
Downloading 359/454: 1-michalko-cdi.0a5.pdf
Downloading 360/454: hatarozatok-181218.152.pdf
Downloading 361/454: 1a-melleklet.9cf.pdf
Downloading 362/454: 2-szakmai-beszamolo-melleklet.20b.pdf
Downloading 363/454: 3b-nii-ugyrend.417.pdf
Downloading 364/454: 3c-jki-ugyrend-modositasa.56a.pdf
Downloading 365/454: 3d-ai-ugyrend.800.pdf

In [8]:
manifest_columns = [
    "sidebar_label",
    "sidebar_url",
    "pdf_label",
    "pdf_url",
    "filename",
    "status",
    "error",
]
pd.DataFrame(pdf_records, columns=manifest_columns).to_csv(
    output_dir / "senate_pdf_manifest.csv",
    index=False,
    encoding="utf-8-sig",
)
pd.DataFrame(not_found_links, columns=["type", "label", "url"]).to_csv(
    output_dir / "senate_404_links.csv",
    index=False,
    encoding="utf-8-sig",
)
pd.DataFrame(
    unauthorized_links,
    columns=["type", "label", "url", "error"],
).to_csv(
    output_dir / "senate_401_links.csv",
    index=False,
    encoding="utf-8-sig",
)
pd.DataFrame(
    connection_error_links,
    columns=["type", "label", "url", "error"],
).to_csv(
    output_dir / "senate_connection_errors.csv",
    index=False,
    encoding="utf-8-sig",
)

downloaded_count = sum(record["status"] == "downloaded" for record in pdf_records)
print(f"Downloaded {downloaded_count} of {len(pdf_records)} PDFs to {output_dir}")
print(f"Saved PDF metadata to {output_dir / 'senate_pdf_manifest.csv'}")
if not_found_links:
    print(
        f"Skipped {len(not_found_links)} links that returned 404; "
        f"details saved to {output_dir / 'senate_404_links.csv'}"
    )
if unauthorized_links:
    print(
        f"Skipped {len(unauthorized_links)} links that returned 401; "
        f"details saved to {output_dir / 'senate_401_links.csv'}"
    )
if connection_error_links:
    print(
        f"Skipped {len(connection_error_links)} links due to connection errors; "
        f"details saved to {output_dir / 'senate_connection_errors.csv'}"
    )

Downloaded 445 of 454 PDFs to D:\Work\Jacob\senate_meeting_minutes
Saved PDF metadata to D:\Work\Jacob\senate_meeting_minutes\senate_pdf_manifest.csv
Skipped 8 links that returned 404; details saved to D:\Work\Jacob\senate_meeting_minutes\senate_404_links.csv
Skipped 1 links due to connection errors; details saved to D:\Work\Jacob\senate_meeting_minutes\senate_connection_errors.csv

In [9]:
pdf_files = pd.DataFrame(pdf_records, columns=manifest_columns).rename(columns={
    'pdf_label': 'label',
    'pdf_url': 'url'
})

In [10]:
pdf_files[:5]

,sidebar_label,sidebar_url,label,url,filename,status,error
0,Szenátus,https://www.uni-corvinus.hu/fooldal/egyetemunk...,Adatkezelési tájékoztató,https://www.uni-corvinus.hu/contents/uploads/2...,AT_Szenátus_240515.bc3.pdf,downloaded,
1,2026/2027,https://www.uni-corvinus.hu/fooldal/egyetemunk...,Írásbeli szavazás elrendelése,https://www.uni-corvinus.hu/downloads/di0f.o8k...,bce-sz-20260928-irasbeli-szavazas-elrendelese-...,downloaded,
2,2026/2027,https://www.uni-corvinus.hu/fooldal/egyetemunk...,Meghívó,https://www.uni-corvinus.hu/downloads/dgpo.ok9...,senate-invitation-260922-sgd.pdf,downloaded,
3,2026/2027,https://www.uni-corvinus.hu/fooldal/egyetemunk...,1. melléklet,https://www.uni-corvinus.hu/downloads/dgqg.m0l...,1-local-resilience.pdf,downloaded,
4,2026/2027,https://www.uni-corvinus.hu/fooldal/egyetemunk...,2. melléklet,https://www.uni-corvinus.hu/downloads/dgqh.16d...,2-nedimarc-neuro-and-digital-marketing.pdf,downloaded,

In [11]:
print("Number of meeting minutes downloaded: {:,}".format(
    pdf_files[pdf_files['label'].str.contains('jegyz', case=False, regex=False)].shape[0]
))

Number of meeting minutes downloaded: 59

In [12]:
pdf_files[pdf_files['label'].str.contains('jegyz', case=False, regex=False)]['status'].value_counts()

status
downloaded    58
404            1
Name: count, dtype: int64

In [13]:
pdf_files[pdf_files['label'].str.contains('jegyz', case=False, regex=False)]['label'].unique()

array(['Jegyzőkönyv', 'Egyetemi Doktori Tanács jegyzőkönyvi kivonata',
       'jegyzokonyv_200512.3b3.pdf'], dtype=object)

In [14]:
pdf_files[pdf_files['label'].str.contains('jegyz', case=False, regex=False)][:5]

,sidebar_label,sidebar_url,label,url,filename,status,error
22,2025/2026,https://www.uni-corvinus.hu/fooldal/egyetemunk...,Jegyzőkönyv,https://www.uni-corvinus.hu/downloads/d4wm.15x...,jegyzokonyv-260603.pdf,downloaded,
37,2025/2026,https://www.uni-corvinus.hu/fooldal/egyetemunk...,Jegyzőkönyv,https://www.uni-corvinus.hu/downloads/cwdy.1ru...,jegyzokonyv-260409.pdf,downloaded,
41,2025/2026,https://www.uni-corvinus.hu/fooldal/egyetemunk...,Jegyzőkönyv,https://www.uni-corvinus.hu/downloads/cv8x.ap3...,jegyzokonyv-260330.pdf,downloaded,
44,2025/2026,https://www.uni-corvinus.hu/fooldal/egyetemunk...,Jegyzőkönyv,https://www.uni-corvinus.hu/downloads/cxp1.bu1...,sz-jegyzokonyv-250317.pdf,downloaded,
48,2025/2026,https://www.uni-corvinus.hu/fooldal/egyetemunk...,Jegyzőkönyv,https://www.uni-corvinus.hu/downloads/dfvm.13b...,sz-jegyzokonyv-260303-ai.pdf,downloaded,

In [15]:
pdf_files = pdf_files[pdf_files['label'].str.contains('jegyz', case=False, regex=False)].copy()

## OCRing the PDFs

In [16]:
import re
import json
from pathlib import Path

import fitz  # PyMuPDF
import pandas as pd

from PIL import Image

In [17]:
OCR_LANGUAGE = "hun"
OCR_DPI = 300

In [18]:
def extract_pdf_text(pdf_path: Path) -> str:
    """
    Extract text from a PDF.

    First tries normal PDF text extraction.
    If the PDF is scanned/image-based, falls back to OCR.
    """

    print(f"Processing: {pdf_path.name}")

    with fitz.open(pdf_path) as doc:

        # -----------------------------------------------------------
        # 1. Try native PDF text extraction
        # -----------------------------------------------------------

        native_text = "\n\n".join(
            page.get_text("text")
            for page in doc
        ).strip()

        # If enough text was extracted, use it
        if len(native_text) > 100:
            print("  -> Native text extraction")
            return native_text

        # -----------------------------------------------------------
        # 2. OCR fallback
        # -----------------------------------------------------------

        print("  -> Scanned PDF detected, using OCR")

        ocr_pages = []

        zoom = OCR_DPI / 72
        matrix = fitz.Matrix(zoom, zoom)

        for page_number, page in enumerate(doc, start=1):

            print(f"     OCR page {page_number}/{len(doc)}")

            # Render page to image
            pix = page.get_pixmap(
                matrix=matrix,
                alpha=False
            )

            image = Image.frombytes(
                "RGB",
                [pix.width, pix.height],
                pix.samples
            )

            # OCR
            text = pytesseract.image_to_string(
                image,
                lang=OCR_LANGUAGE,
                config="--psm 3"
            )

            ocr_pages.append(text.strip())

        return "\n\n".join(ocr_pages)

In [19]:
import pytesseract

pytesseract.pytesseract.tesseract_cmd = r"C:\Program Files\Tesseract-OCR\tesseract.exe"

print(pytesseract.get_languages())

['eng', 'hun', 'osd']

In [21]:
pdf_files['filename'][:5]

22          jegyzokonyv-260603.pdf
37          jegyzokonyv-260409.pdf
41          jegyzokonyv-260330.pdf
44       sz-jegyzokonyv-250317.pdf
48    sz-jegyzokonyv-260303-ai.pdf
Name: filename, dtype: object

In [24]:
if not Path(WORK_DIR).exists():
    raise FileNotFoundError(
        f"Output directory does not exist: {WORK_DIR}"
    )

files_to_ocr = []
for f in pdf_files['filename'].values:
    if Path(WORK_DIR + "/" + f).exists():
        files_to_ocr.append(Path(WORK_DIR + "/" + f))
    else:
        print("Missing: {}".format(WORK_DIR + "/" + f))

print(f"Found {len(files_to_ocr)} PDF files\n")

Missing: senate_meeting_minutes/SZ_jegyzokonyv_220316.b06.pdf
Found 58 PDF files

In [25]:
# ---------------------------------------------------------
# Checkpoint configuration
# ---------------------------------------------------------

CHECKPOINT_FILE = Path(WORK_DIR) / "extraction_checkpoint.json"

# Load existing checkpoint if available
if CHECKPOINT_FILE.exists():
    try:
        with CHECKPOINT_FILE.open("r", encoding="utf-8") as f:
            records = json.load(f)

        print(
            f"Loaded checkpoint: {len(records)} PDFs already processed\n"
        )

    except (json.JSONDecodeError, OSError) as e:
        print(f"Could not load checkpoint: {e}")
        print("Starting with an empty checkpoint.\n")
        records = []
else:
    records = []


# Keep track of files already successfully processed
processed_files = {
    record["filename"]
    for record in records
}


# ---------------------------------------------------------
# Process PDFs
# ---------------------------------------------------------

for pdf_path in files_to_ocr:
    # Skip files already successfully processed
    if pdf_path.name in processed_files:
        print(f"SKIP: {pdf_path.name}")
        continue

    print(f"Processing: {pdf_path.name}")

    try:
        text = extract_pdf_text(pdf_path)

        # Extract year from filename, e.g.
        # 2020_some_document.pdf -> 2020
        year_match = re.match(
            r"^(\d{4})_",
            pdf_path.name
        )

        year = (
            int(year_match.group(1))
            if year_match
            else None
        )

        record = {
            "year": year,
            "filename": pdf_path.name,
            "text": text,
        }

        records.append(record)

        # -------------------------------------------------
        # Save checkpoint immediately after each PDF
        # -------------------------------------------------

        with CHECKPOINT_FILE.open(
            "w",
            encoding="utf-8"
        ) as f:
            json.dump(
                records,
                f,
                ensure_ascii=False,
                indent=2
            )

        processed_files.add(pdf_path.name)

        print(
            f"  Extracted {len(text):,} characters"
        )
        print(
            f"  Checkpoint saved ({len(records)} PDFs)\n"
        )

    except Exception as e:
        print(
            f"ERROR processing {pdf_path.name}: {e}\n"
        )

Processing: jegyzokonyv-260603.pdf
Processing: jegyzokonyv-260603.pdf
  -> Native text extraction
  Extracted 1,910 characters
  Checkpoint saved (1 PDFs)

Processing: jegyzokonyv-260409.pdf
Processing: jegyzokonyv-260409.pdf
  -> Native text extraction
  Extracted 1,868 characters
  Checkpoint saved (2 PDFs)

Processing: jegyzokonyv-260330.pdf
Processing: jegyzokonyv-260330.pdf
  -> Native text extraction
  Extracted 3,569 characters
  Checkpoint saved (3 PDFs)

Processing: sz-jegyzokonyv-250317.pdf
Processing: sz-jegyzokonyv-250317.pdf
  -> Native text extraction
  Extracted 34,889 characters
  Checkpoint saved (4 PDFs)

Processing: sz-jegyzokonyv-260303-ai.pdf
Processing: sz-jegyzokonyv-260303-ai.pdf
  -> Scanned PDF detected, using OCR
     OCR page 1/22
     OCR page 2/22
     OCR page 3/22
     OCR page 4/22
     OCR page 5/22
     OCR page 6/22
     OCR page 7/22
     OCR page 8/22
     OCR page 9/22
     OCR page 10/22
     OCR page 11/22
     OCR page 12/22
     OCR page 13/22
     OCR page 14/22
     OCR page 15/22
     OCR page 16/22
     OCR page 17/22
     OCR page 18/22
     OCR page 19/22
     OCR page 20/22
     OCR page 21/22
     OCR page 22/22
  Extracted 68,055 characters
  Checkpoint saved (5 PDFs)

Processing: sz-jegyzokonyv-260127.pdf
Processing: sz-jegyzokonyv-260127.pdf
  -> Native text extraction
  Extracted 19,336 characters
  Checkpoint saved (6 PDFs)

Processing: jegyzokonyv-260109-ai.pdf
Processing: jegyzokonyv-260109-ai.pdf
  -> Scanned PDF detected, using OCR
     OCR page 1/1
  Extracted 2,288 characters
  Checkpoint saved (7 PDFs)

Processing: jegyzokonyv-251218-ai.pdf
Processing: jegyzokonyv-251218-ai.pdf
  -> Scanned PDF detected, using OCR
     OCR page 1/2
     OCR page 2/2
  Extracted 2,456 characters
  Checkpoint saved (8 PDFs)

Processing: sz-jegyzokonyv-251211-c.pdf
Processing: sz-jegyzokonyv-251211-c.pdf
  -> Native text extraction
  Extracted 84,330 characters
  Checkpoint saved (9 PDFs)

Processing: sz-jegyzokonyv-251118-c.pdf
Processing: sz-jegyzokonyv-251118-c.pdf
  -> Native text extraction
  Extracted 34,307 characters
  Checkpoint saved (10 PDFs)

Processing: jegyzokonyv-nyers-251014.pdf
Processing: jegyzokonyv-nyers-251014.pdf
  -> Native text extraction
  Extracted 75,592 characters
  Checkpoint saved (11 PDFs)

Processing: sz-jegyzokonyv-250916-ai.pdf
Processing: sz-jegyzokonyv-250916-ai.pdf
  -> Scanned PDF detected, using OCR
     OCR page 1/18
     OCR page 2/18
     OCR page 3/18
     OCR page 4/18
     OCR page 5/18
     OCR page 6/18
     OCR page 7/18
     OCR page 8/18
     OCR page 9/18
     OCR page 10/18
     OCR page 11/18
     OCR page 12/18
     OCR page 13/18
     OCR page 14/18
     OCR page 15/18
     OCR page 16/18
     OCR page 17/18
     OCR page 18/18
  Extracted 57,364 characters
  Checkpoint saved (12 PDFs)

Processing: jegyzokonyv-250714-alairt.pdf
Processing: jegyzokonyv-250714-alairt.pdf
  -> Scanned PDF detected, using OCR
     OCR page 1/1
  Extracted 1,927 characters
  Checkpoint saved (13 PDFs)

Processing: jegyzokonyv-nyers-valtozat.pdf
Processing: jegyzokonyv-nyers-valtozat.pdf
  -> Native text extraction
  Extracted 108,106 characters
  Checkpoint saved (14 PDFs)

Processing: jegyzokonyv-250602.pdf
Processing: jegyzokonyv-250602.pdf
  -> Native text extraction
  Extracted 1,969 characters
  Checkpoint saved (15 PDFs)

Processing: sz-jegyzokonyv-250520-ai.pdf
Processing: sz-jegyzokonyv-250520-ai.pdf
  -> Scanned PDF detected, using OCR
     OCR page 1/14
     OCR page 2/14
     OCR page 3/14
     OCR page 4/14
     OCR page 5/14
     OCR page 6/14
     OCR page 7/14
     OCR page 8/14
     OCR page 9/14
     OCR page 10/14
     OCR page 11/14
     OCR page 12/14
     OCR page 13/14
     OCR page 14/14
  Extracted 40,867 characters
  Checkpoint saved (16 PDFs)

Processing: jegyzokonyv-20250415-sgd.pdf
Processing: jegyzokonyv-20250415-sgd.pdf
  -> Scanned PDF detected, using OCR
     OCR page 1/12
     OCR page 2/12
     OCR page 3/12
     OCR page 4/12
     OCR page 5/12
     OCR page 6/12
     OCR page 7/12
     OCR page 8/12
     OCR page 9/12
     OCR page 10/12
     OCR page 11/12
     OCR page 12/12
  Extracted 32,433 characters
  Checkpoint saved (17 PDFs)

Processing: sz-jegyzokonyv-250318-ai.pdf
Processing: sz-jegyzokonyv-250318-ai.pdf
  -> Scanned PDF detected, using OCR
     OCR page 1/18
     OCR page 2/18
     OCR page 3/18
     OCR page 4/18
     OCR page 5/18
     OCR page 6/18
     OCR page 7/18
     OCR page 8/18
     OCR page 9/18
     OCR page 10/18
     OCR page 11/18
     OCR page 12/18
     OCR page 13/18
     OCR page 14/18
     OCR page 15/18
     OCR page 16/18
     OCR page 17/18
     OCR page 18/18
  Extracted 45,565 characters
  Checkpoint saved (18 PDFs)

Processing: minutes-250218.pdf
Processing: minutes-250218.pdf
  -> Native text extraction
  Extracted 60,549 characters
  Checkpoint saved (19 PDFs)

Processing: sz-jegyzokonyv-241210-sgd.pdf
Processing: sz-jegyzokonyv-241210-sgd.pdf
  -> Scanned PDF detected, using OCR
     OCR page 1/24
     OCR page 2/24
     OCR page 3/24
     OCR page 4/24
     OCR page 5/24
     OCR page 6/24
     OCR page 7/24
     OCR page 8/24
     OCR page 9/24
     OCR page 10/24
     OCR page 11/24
     OCR page 12/24
     OCR page 13/24
     OCR page 14/24
     OCR page 15/24
     OCR page 16/24
     OCR page 17/24
     OCR page 18/24
     OCR page 19/24
     OCR page 20/24
     OCR page 21/24
     OCR page 22/24
     OCR page 23/24
     OCR page 24/24
  Extracted 60,927 characters
  Checkpoint saved (20 PDFs)

Processing: sz-jegyzokonyv-241112-sgd.pdf
Processing: sz-jegyzokonyv-241112-sgd.pdf
  -> Scanned PDF detected, using OCR
     OCR page 1/16
     OCR page 2/16
     OCR page 3/16
     OCR page 4/16
     OCR page 5/16
     OCR page 6/16
     OCR page 7/16
     OCR page 8/16
     OCR page 9/16
     OCR page 10/16
     OCR page 11/16
     OCR page 12/16
     OCR page 13/16
     OCR page 14/16
     OCR page 15/16
     OCR page 16/16
  Extracted 46,106 characters
  Checkpoint saved (21 PDFs)

Processing: jegyzokonyv-241024.pdf
Processing: jegyzokonyv-241024.pdf
  -> Native text extraction
  Extracted 1,949 characters
  Checkpoint saved (22 PDFs)

Processing: jegyzokonyv-240924.pdf
Processing: jegyzokonyv-240924.pdf
  -> Native text extraction
  Extracted 2,143 characters
  Checkpoint saved (23 PDFs)

Processing: jegyzokonyv-240822.pdf
Processing: jegyzokonyv-240822.pdf
  -> Native text extraction
  Extracted 1,957 characters
  Checkpoint saved (24 PDFs)

Processing: sz-jegyzokonyv-240716-sgn.pdf
Processing: sz-jegyzokonyv-240716-sgn.pdf
  -> Scanned PDF detected, using OCR
     OCR page 1/22
     OCR page 2/22
     OCR page 3/22
     OCR page 4/22
     OCR page 5/22
     OCR page 6/22
     OCR page 7/22
     OCR page 8/22
     OCR page 9/22
     OCR page 10/22
     OCR page 11/22
     OCR page 12/22
     OCR page 13/22
     OCR page 14/22
     OCR page 15/22
     OCR page 16/22
     OCR page 17/22
     OCR page 18/22
     OCR page 19/22
     OCR page 20/22
     OCR page 21/22
     OCR page 22/22
  Extracted 61,967 characters
  Checkpoint saved (25 PDFs)

Processing: sz-jegyzokonyv-240611.pdf
Processing: sz-jegyzokonyv-240611.pdf
  -> Native text extraction
  Extracted 109,625 characters
  Checkpoint saved (26 PDFs)

Processing: SZ_jegyzokonyv_240522.da9.pdf
Processing: SZ_jegyzokonyv_240522.da9.pdf
  -> Native text extraction
  Extracted 42,605 characters
  Checkpoint saved (27 PDFs)

Processing: SZ_jegyzokonyv_240507.b0a.pdf
Processing: SZ_jegyzokonyv_240507.b0a.pdf
  -> Scanned PDF detected, using OCR
     OCR page 1/30
     OCR page 2/30
     OCR page 3/30
     OCR page 4/30
     OCR page 5/30
     OCR page 6/30
     OCR page 7/30
     OCR page 8/30
     OCR page 9/30
     OCR page 10/30
     OCR page 11/30
     OCR page 12/30
     OCR page 13/30
     OCR page 14/30
     OCR page 15/30
     OCR page 16/30
     OCR page 17/30
     OCR page 18/30
     OCR page 19/30
     OCR page 20/30
     OCR page 21/30
     OCR page 22/30
     OCR page 23/30
     OCR page 24/30
     OCR page 25/30
     OCR page 26/30
     OCR page 27/30
     OCR page 28/30
     OCR page 29/30
     OCR page 30/30
  Extracted 98,731 characters
  Checkpoint saved (28 PDFs)

Processing: jegyzokonyv_240508.1dc.pdf
Processing: jegyzokonyv_240508.1dc.pdf
  -> Native text extraction
  Extracted 3,103 characters
  Checkpoint saved (29 PDFs)

Processing: sz-jegyzokonyv-240409-alairt.pdf
Processing: sz-jegyzokonyv-240409-alairt.pdf
  -> Scanned PDF detected, using OCR
     OCR page 1/22
     OCR page 2/22
     OCR page 3/22
     OCR page 4/22
     OCR page 5/22
     OCR page 6/22
     OCR page 7/22
     OCR page 8/22
     OCR page 9/22
     OCR page 10/22
     OCR page 11/22
     OCR page 12/22
     OCR page 13/22
     OCR page 14/22
     OCR page 15/22
     OCR page 16/22
     OCR page 17/22
     OCR page 18/22
     OCR page 19/22
     OCR page 20/22
     OCR page 21/22
     OCR page 22/22
  Extracted 63,641 characters
  Checkpoint saved (30 PDFs)

Processing: SZ_jegyzokonyv_240312.d1e.pdf
Processing: SZ_jegyzokonyv_240312.d1e.pdf
  -> Scanned PDF detected, using OCR
     OCR page 1/8
     OCR page 2/8
     OCR page 3/8
     OCR page 4/8
     OCR page 5/8
     OCR page 6/8
     OCR page 7/8
     OCR page 8/8
  Extracted 19,712 characters
  Checkpoint saved (31 PDFs)

Processing: SZ_jegyzokonyv_240229.40d.pdf
Processing: SZ_jegyzokonyv_240229.40d.pdf
  -> Scanned PDF detected, using OCR
     OCR page 1/14
     OCR page 2/14
     OCR page 3/14
     OCR page 4/14
     OCR page 5/14
     OCR page 6/14
     OCR page 7/14
     OCR page 8/14
     OCR page 9/14
     OCR page 10/14
     OCR page 11/14
     OCR page 12/14
     OCR page 13/14
     OCR page 14/14
  Extracted 42,374 characters
  Checkpoint saved (32 PDFs)

Processing: SZ_jegyzokonyv_240213.0a4.pdf
Processing: SZ_jegyzokonyv_240213.0a4.pdf
  -> Scanned PDF detected, using OCR
     OCR page 1/44
     OCR page 2/44
     OCR page 3/44
     OCR page 4/44
     OCR page 5/44
     OCR page 6/44
     OCR page 7/44
     OCR page 8/44
     OCR page 9/44
     OCR page 10/44
     OCR page 11/44
     OCR page 12/44
     OCR page 13/44
     OCR page 14/44
     OCR page 15/44
     OCR page 16/44
     OCR page 17/44
     OCR page 18/44
     OCR page 19/44
     OCR page 20/44
     OCR page 21/44
     OCR page 22/44
     OCR page 23/44
     OCR page 24/44
     OCR page 25/44
     OCR page 26/44
     OCR page 27/44
     OCR page 28/44
     OCR page 29/44
     OCR page 30/44
     OCR page 31/44
     OCR page 32/44
     OCR page 33/44
     OCR page 34/44
     OCR page 35/44
     OCR page 36/44
     OCR page 37/44
     OCR page 38/44
     OCR page 39/44
     OCR page 40/44
     OCR page 41/44
     OCR page 42/44
     OCR page 43/44
     OCR page 44/44
  Extracted 162,170 characters
  Checkpoint saved (33 PDFs)

Processing: SZ_jegyzokonyv_240116.203.pdf
Processing: SZ_jegyzokonyv_240116.203.pdf
  -> Scanned PDF detected, using OCR
     OCR page 1/50
     OCR page 2/50
     OCR page 3/50
     OCR page 4/50
     OCR page 5/50
     OCR page 6/50
     OCR page 7/50
     OCR page 8/50
     OCR page 9/50
     OCR page 10/50
     OCR page 11/50
     OCR page 12/50
     OCR page 13/50
     OCR page 14/50
     OCR page 15/50
     OCR page 16/50
     OCR page 17/50
     OCR page 18/50
     OCR page 19/50
     OCR page 20/50
     OCR page 21/50
     OCR page 22/50
     OCR page 23/50
     OCR page 24/50
     OCR page 25/50
     OCR page 26/50
     OCR page 27/50
     OCR page 28/50
     OCR page 29/50
     OCR page 30/50
     OCR page 31/50
     OCR page 32/50
     OCR page 33/50
     OCR page 34/50
     OCR page 35/50
     OCR page 36/50
     OCR page 37/50
     OCR page 38/50
     OCR page 39/50
     OCR page 40/50
     OCR page 41/50
     OCR page 42/50
     OCR page 43/50
     OCR page 44/50
     OCR page 45/50
     OCR page 46/50
     OCR page 47/50
     OCR page 48/50
     OCR page 49/50
     OCR page 50/50
  Extracted 174,612 characters
  Checkpoint saved (34 PDFs)

Processing: jegyzokonyv_231220.f4f.pdf
Processing: jegyzokonyv_231220.f4f.pdf
  -> Native text extraction
  Extracted 3,043 characters
  Checkpoint saved (35 PDFs)

Processing: SZ_jegyzokonyv_231205.e0f.pdf
Processing: SZ_jegyzokonyv_231205.e0f.pdf
  -> Scanned PDF detected, using OCR
     OCR page 1/24
     OCR page 2/24
     OCR page 3/24
     OCR page 4/24
     OCR page 5/24
     OCR page 6/24
     OCR page 7/24
     OCR page 8/24
     OCR page 9/24
     OCR page 10/24
     OCR page 11/24
     OCR page 12/24
     OCR page 13/24
     OCR page 14/24
     OCR page 15/24
     OCR page 16/24
     OCR page 17/24
     OCR page 18/24
     OCR page 19/24
     OCR page 20/24
     OCR page 21/24
     OCR page 22/24
     OCR page 23/24
     OCR page 24/24
  Extracted 67,996 characters
  Checkpoint saved (36 PDFs)

Processing: SZ_jegyzokonyv_231114.5c9.pdf
Processing: SZ_jegyzokonyv_231114.5c9.pdf
  -> Scanned PDF detected, using OCR
     OCR page 1/38
     OCR page 2/38
     OCR page 3/38
     OCR page 4/38
     OCR page 5/38
     OCR page 6/38
     OCR page 7/38
     OCR page 8/38
     OCR page 9/38
     OCR page 10/38
     OCR page 11/38
     OCR page 12/38
     OCR page 13/38
     OCR page 14/38
     OCR page 15/38
     OCR page 16/38
     OCR page 17/38
     OCR page 18/38
     OCR page 19/38
     OCR page 20/38
     OCR page 21/38
     OCR page 22/38
     OCR page 23/38
     OCR page 24/38
     OCR page 25/38
     OCR page 26/38
     OCR page 27/38
     OCR page 28/38
     OCR page 29/38
     OCR page 30/38
     OCR page 31/38
     OCR page 32/38
     OCR page 33/38
     OCR page 34/38
     OCR page 35/38
     OCR page 36/38
     OCR page 37/38
     OCR page 38/38
  Extracted 131,798 characters
  Checkpoint saved (37 PDFs)

Processing: SZ_jegyzokonyv_231107.9c0.pdf
Processing: SZ_jegyzokonyv_231107.9c0.pdf
  -> Scanned PDF detected, using OCR
     OCR page 1/50
     OCR page 2/50
     OCR page 3/50
     OCR page 4/50
     OCR page 5/50
     OCR page 6/50
     OCR page 7/50
     OCR page 8/50
     OCR page 9/50
     OCR page 10/50
     OCR page 11/50
     OCR page 12/50
     OCR page 13/50
     OCR page 14/50
     OCR page 15/50
     OCR page 16/50
     OCR page 17/50
     OCR page 18/50
     OCR page 19/50
     OCR page 20/50
     OCR page 21/50
     OCR page 22/50
     OCR page 23/50
     OCR page 24/50
     OCR page 25/50
     OCR page 26/50
     OCR page 27/50
     OCR page 28/50
     OCR page 29/50
     OCR page 30/50
     OCR page 31/50
     OCR page 32/50
     OCR page 33/50
     OCR page 34/50
     OCR page 35/50
     OCR page 36/50
     OCR page 37/50
     OCR page 38/50
     OCR page 39/50
     OCR page 40/50
     OCR page 41/50
     OCR page 42/50
     OCR page 43/50
     OCR page 44/50
     OCR page 45/50
     OCR page 46/50
     OCR page 47/50
     OCR page 48/50
     OCR page 49/50
     OCR page 50/50
  Extracted 163,792 characters
  Checkpoint saved (38 PDFs)

Processing: jegyzokonyv_231018_alairt.60a.pdf
Processing: jegyzokonyv_231018_alairt.60a.pdf
  -> Scanned PDF detected, using OCR
     OCR page 1/1
  Extracted 1,920 characters
  Checkpoint saved (39 PDFs)

Processing: SZ_jegyzokonyv_231010_alairt.214.pdf
Processing: SZ_jegyzokonyv_231010_alairt.214.pdf
  -> Scanned PDF detected, using OCR
     OCR page 1/32
     OCR page 2/32
     OCR page 3/32
     OCR page 4/32
     OCR page 5/32
     OCR page 6/32
     OCR page 7/32
     OCR page 8/32
     OCR page 9/32
     OCR page 10/32
     OCR page 11/32
     OCR page 12/32
     OCR page 13/32
     OCR page 14/32
     OCR page 15/32
     OCR page 16/32
     OCR page 17/32
     OCR page 18/32
     OCR page 19/32
     OCR page 20/32
     OCR page 21/32
     OCR page 22/32
     OCR page 23/32
     OCR page 24/32
     OCR page 25/32
     OCR page 26/32
     OCR page 27/32
     OCR page 28/32
     OCR page 29/32
     OCR page 30/32
     OCR page 31/32
     OCR page 32/32
  Extracted 105,584 characters
  Checkpoint saved (40 PDFs)

Processing: SZ_jegyzokonyv_230912.a16.pdf
Processing: SZ_jegyzokonyv_230912.a16.pdf
  -> Scanned PDF detected, using OCR
     OCR page 1/20
     OCR page 2/20
     OCR page 3/20
     OCR page 4/20
     OCR page 5/20
     OCR page 6/20
     OCR page 7/20
     OCR page 8/20
     OCR page 9/20
     OCR page 10/20
     OCR page 11/20
     OCR page 12/20
     OCR page 13/20
     OCR page 14/20
     OCR page 15/20
     OCR page 16/20
     OCR page 17/20
     OCR page 18/20
     OCR page 19/20
     OCR page 20/20
  Extracted 70,919 characters
  Checkpoint saved (41 PDFs)

Processing: SZ_jegyzokonyv_230711.564.pdf
Processing: SZ_jegyzokonyv_230711.564.pdf
  -> Scanned PDF detected, using OCR
     OCR page 1/60
     OCR page 2/60
     OCR page 3/60
     OCR page 4/60
     OCR page 5/60
     OCR page 6/60
     OCR page 7/60
     OCR page 8/60
     OCR page 9/60
     OCR page 10/60
     OCR page 11/60
     OCR page 12/60
     OCR page 13/60
     OCR page 14/60
     OCR page 15/60
     OCR page 16/60
     OCR page 17/60
     OCR page 18/60
     OCR page 19/60
     OCR page 20/60
     OCR page 21/60
     OCR page 22/60
     OCR page 23/60
     OCR page 24/60
     OCR page 25/60
     OCR page 26/60
     OCR page 27/60
     OCR page 28/60
     OCR page 29/60
     OCR page 30/60
     OCR page 31/60
     OCR page 32/60
     OCR page 33/60
     OCR page 34/60
     OCR page 35/60
     OCR page 36/60
     OCR page 37/60
     OCR page 38/60
     OCR page 39/60
     OCR page 40/60
     OCR page 41/60
     OCR page 42/60
     OCR page 43/60
     OCR page 44/60
     OCR page 45/60
     OCR page 46/60
     OCR page 47/60
     OCR page 48/60
     OCR page 49/60
     OCR page 50/60
     OCR page 51/60
     OCR page 52/60
     OCR page 53/60
     OCR page 54/60
     OCR page 55/60
     OCR page 56/60
     OCR page 57/60
     OCR page 58/60
     OCR page 59/60
     OCR page 60/60
  Extracted 203,518 characters
  Checkpoint saved (42 PDFs)

Processing: SZ_jegyzokonyv_230509.5cf.pdf
Processing: SZ_jegyzokonyv_230509.5cf.pdf
  -> Scanned PDF detected, using OCR
     OCR page 1/42
     OCR page 2/42
     OCR page 3/42
     OCR page 4/42
     OCR page 5/42
     OCR page 6/42
     OCR page 7/42
     OCR page 8/42
     OCR page 9/42
     OCR page 10/42
     OCR page 11/42
     OCR page 12/42
     OCR page 13/42
     OCR page 14/42
     OCR page 15/42
     OCR page 16/42
     OCR page 17/42
     OCR page 18/42
     OCR page 19/42
     OCR page 20/42
     OCR page 21/42
     OCR page 22/42
     OCR page 23/42
     OCR page 24/42
     OCR page 25/42
     OCR page 26/42
     OCR page 27/42
     OCR page 28/42
     OCR page 29/42
     OCR page 30/42
     OCR page 31/42
     OCR page 32/42
     OCR page 33/42
     OCR page 34/42
     OCR page 35/42
     OCR page 36/42
     OCR page 37/42
     OCR page 38/42
     OCR page 39/42
     OCR page 40/42
     OCR page 41/42
     OCR page 42/42
  Extracted 148,871 characters
  Checkpoint saved (43 PDFs)

Processing: SZ_jegyzokonyv_230404.da4.pdf
Processing: SZ_jegyzokonyv_230404.da4.pdf
  -> Scanned PDF detected, using OCR
     OCR page 1/34
     OCR page 2/34
     OCR page 3/34
     OCR page 4/34
     OCR page 5/34
     OCR page 6/34
     OCR page 7/34
     OCR page 8/34
     OCR page 9/34
     OCR page 10/34
     OCR page 11/34
     OCR page 12/34
     OCR page 13/34
     OCR page 14/34
     OCR page 15/34
     OCR page 16/34
     OCR page 17/34
     OCR page 18/34
     OCR page 19/34
     OCR page 20/34
     OCR page 21/34
     OCR page 22/34
     OCR page 23/34
     OCR page 24/34
     OCR page 25/34
     OCR page 26/34
     OCR page 27/34
     OCR page 28/34
     OCR page 29/34
     OCR page 30/34
     OCR page 31/34
     OCR page 32/34
     OCR page 33/34
     OCR page 34/34
  Extracted 113,959 characters
  Checkpoint saved (44 PDFs)

Processing: SZ_jegyzokonyv_230207.470.pdf
Processing: SZ_jegyzokonyv_230207.470.pdf
  -> Scanned PDF detected, using OCR
     OCR page 1/21
     OCR page 2/21
     OCR page 3/21
     OCR page 4/21

In [26]:
from Helper import Log

In [27]:
df = pd.DataFrame(records)

In [28]:
import statistics

print("Average length of OCRd text: {:,.2f}".format(
    statistics.mean([i for i in df['text'].str.len()])
))

Average length of OCRd text: 63,629.76

In [29]:
with Log.save_file(WORK_DIR + "/output/senate_meeting_minutes_hun.csv") as filename:
    df.to_csv(filename, index=False)

File saved to `senate_meeting_minutes\output\senate_meeting_minutes_hun_202610011325.csv` (3.7MB)

In [33]:
# Not a meeting minute
print(df.loc[0, 'text'])

SZENÁTUS
Ülésen kívüli szavazás
küldi:
Jog és Beszerzés
e-mail:
szenatus@uni-corvinus.hu
dátum:
2026. június 4.



JEGYZŐKÖNYV
a Szenátus ülésen kívüli szavazásának lezárásáról

SZ-XV/2025/2026. (VI. 3.)

Bruno Joseph T. van Pottelsberghe de la Potterie, elnök-rektor a Szervezeti és Működési
Rend 10. § (16) bekezdése alapján a Szenátus összehívása helyett ülésen kívül történő
szavazást rendelt el az alábbi témában:

1. Egyetemi Doktori Szabályzat módosításának jóváhagyása
Előterjesztő: Előterjesztő: Bartus Tamás, kutatási és akadémiai közösségért felelős
rektorhelyettes

Az írásbeli szavazás elrendelésének időpontja: 2026. május 29.
A szavazati jog gyakorlásának időtartama:
2026. június 3. (szerda) 8:00 óra – 2026. június 3. (szerda) 16:30 óra

A szavazatszámláló bizottság tagjai:
-
Kónya István Tamás, a Szenátus tagja
-
K. Szabó Áron, a Szenátus tagja
-
Toronyai Gábor, a Szenátus tagja

A szavazatszámláló bizottság Teams értekezlet keretében tartotta meg ülését és a NEPTUN
egységes tanulmányi rendszer UNIPOLL moduljában ellenőrizte a szavazatokat.

A szavazatszámláló bizottság ülésének kezdete: 2026. június 4. (csütörtök), 9:40 óra

A szavazatszámláló bizottság ülésének vége: 2026. június 4. (csütörtök), 9:45 óra

A 2026. június 3-i ülésen kívüli (írásbeli) szavazáson hozott határozat(ok):

SZ-45/2025/2026. (2026. VI. 3.) számú határozat
A Szenátus elfogadta az Egyetemi Doktori Szabályzat módosítását az előterjesztés szerinti
tartalommal.

Beérkezett szavazatok száma: 26
Érvényes szavazatok száma: 26
Érvényes szavazatok megoszlása: 24 igen, 0 nem, 2 tartózkodás
Szavazásra jogosult szenátusi tagok száma: 32




A szavazatszámláló bizottság megállapította, hogy a szavazás érvényes és eredményes
volt.
Kmf.


……………………………………

a Szenátus tagja
……………………………………

a Szenátus tagja

……………………………………

a Szenátus tagja

In [36]:
# Meeting minute
print(df.loc[3, 'text'])

—————
1 | 10

Bruno van Pottelsberghe: Jó napot kívánok, welcome to all of you, to all the Senate
members and the guests.
We will start with the certificate awards. You know that it has become a tradition at
Corvinus for years to celebrate the academic advancement of our colleagues, our
newly joined faculty and researchers, as well as the Univeristy’s new Professors
Emeriti. And so we have a long series of colleagues who have been appointed or
promoted and I think it's important for us to celebrate this together because they join
our community. And so we will start this Senate by giving them the certificate and a
small gift. And if you allow me, I will stand because today we have many of them.
And so I start with Róbert Imre Csehi, Institute of Social and Political Science,
Associate Professor. Nóra Ágota Felföldi-Szűcs, Associate Professor, Institute of
Finance. Assistant Professor, Institute of Marketing and Communication Sciences,
Evelin Horváth. Assistant Professor, Institute of Data Analytics and Information
Systems, Virág Ilyés. Assistant Professor, Institute of Economics, Emese Kovács.
Lecturer, Institute of Accounting and Law, Norbert Kozma. Associate Professor,
Institute of Social and Political Sciences, Daniela-Sabina Schnell. Assistant
Professor, Institute of Operations and Decision Sciences, Péter Ádám Szentesi.
Assistant Professor Institute of Strategy and Management, Rita Tóth. Associate
Professor, Institute of Sustainable Development, Zsófia Vetőné Mózner. And last but
not least, Senior Research Fellow and Head of CIAS Center for Collective Learning,
Johannes Wachs. And who is unable to attend in person is, Institute of Accounting
and Law, Senior lecturer, Gábor János Dudás.
I would like to announce that several colleagues are excused and Márta Aranyossy,
János Lukacs and Zsuzsanna Hartel-Török are excused for today. Of the 32
members, 29 are present. So there is a quorum. So now, I'm asking you to vote to
check whether the machine works. It works, the vote was successful.
About the agenda, Róbert Marciniák addressed the members of the Senate in a letter
please requesting information regarding the research centers and I request Vice-
Rector Tamás Bartus, responsible for research centers, to report on the operation of
the research centers at the next meeting of the Senate based on the aspect traced
by the Senate or I know that they have already exchanged viewpoint, but you will
report on this at the next Senate, okay? A second letter has been received by Eszter
Kirs. She has sent to all the members of the Senate a letter regarding a cancelled
conference about the V4 region. And I would like to inform you that we will answer
the questions in the miscellaneous section after this agenda.
And so we are supposed now to vote to accept the agenda that you have received.
(Agenda item 1) Adoption of the Code of Ethics and the Rules of Procedure of
the Ethics Committee
Submitter: Bruno van Pottelsberghe, President-Rector
Bruno van Pottelsberghe: So the first agenda item is adoption of the Code of Ethics
and the Rules of Procedures of the Ethics Committee. I am the submitter, but of
course many colleagues have been involved, in particular Zsuzsanna Borbás, and I
would like to thank all those who have been involved. So you know that the former


—————
2 | 10

document, the former Code of Ethics dated from 15 years ago. So it was a time to
revisit it. Some information on what drove the changes is that it should have been
adopted for the new university strategy, the university values, the participants who
contributed to it includes many stakeholders. And I think it's important to remind from
time to time that they are active in contributing to our sessions. And I'd like to thank
the Board of Professors, the Center for Economic Ethics, the Trade Union, the
Corvinus Employee Council, the heads of institutes, the Students’ Union, and the
ERS HUB who have all significantly contributed to this final version, the final draft. So
the most important changes include the new values, the new university values, the
new areas in focus including social responsibility, sustainability, transparency and
scientific integrity. The new committee which is defined in the document, and new
rules of procedures. And after the approval, the university has to submit to the
Senate the employer's disciplinary regulation, and currently we don't have such. So
we still have room for questions and remark. It's already a document that has been
discussed quite intensively. And we will vote after the comments, of course. Do we
have comments or remark on this final draft? Gábor Toronyai.
Gábor Toronyai: I thank Zsuzsanna for the sincere and fair consultation and
coordination. I know this regulation is needed for the university for its EQUIS
accreditation. I believe the text is now acceptable. I hope, however, we will have the
opportunity to improve it. Thank you.
Bruno van Pottelsberghe: Thank you for your comment. Yes, like any part of our
rules and operation procedures, we are free to reconsider and to revisit any of our
rules and procedures including this one. And I think that after one or two years, when
we have a few cases, hopefully not too many, but when we have, we'll be able to
assess whether it's effective, whether we do a fair and effective job applying these
new rules.
I don't see any comments and so I invite you to vote and the proposed text of the
resolution. The Senate supports the adoption of the Code of Ethics and Rules of
Procedures of the Ethics Committee, (Annex 1 of the Code of Ethics) in Hungarian
and English with the addition that the election of the members of the Ethics
Committee must take place within 45 days following the adoption of the Code of
Ethics. And I invite you to vote.
Bruno van Pottelsberghe: You have the right to be happy and thank you for this
impressive work that you did. Thank you.
(Agenda item 2) Amendment of the Rules of Procedure of the Senate
Submitter: Bruno van Pottelsberghe, President-Rector
Bruno van Pottelsberghe: Agenda item two, amendment of the Rules of Procedure
of the Senate. I'm again the submitter.
And as you are aware, the Organisational and Operational Procedures, the OOP has
been amended. And as a result, the administration of the Senate has been
transferred from Legal and Procurement Services to the Rector’s direct authority.
Following the decision of the Board of Trustees, this change is set to enter into force


—————
3 | 10

on April 1st 2026. In order to maintain consistency with the updated OOP, it is now
necessary to reflect these changes in the Senate's own Rules of Procedure. Based
on the above, I ask the Senate to vote on the proposal to amend the Rules of
Procedure. Do we have questions or remarks? Gábor Klimkó.
Gábor Klimkó: Thank you. Dear Rector, respected senators, I'm going to abstain
and I'm going to give you a justification for that. First of all, this change is none of my
business. If it's better for you, for the rector, that's his business. So there is no
problem with that. However, if you go on the text of the proposal itself, it has a
section with the title Purpose and Reasons for the Proposal. And it says, After the
decision of the Board of Trustees, it follows. We don't know the decisions of the
Board of Trustees. These are not disclosed documents. So that's a reason for
something I'm not really aware of. And this is a very bad practice. So even in this
situation, when it doesn't matter to tell the truth for me, if it's better for you than do it,
then I'm going to give you a weak yes, which is an abstain, but I want to emphasize
here that this is not a proper justification for such a proposal. Thank you very much.
Bruno van Pottelsberghe: Thank you. Any other comments or remarks? No. So I
invite you to vote and the proposed text of the resolution. The Senate supports the
amendment of the Rules of Procedure of the Senate in Hungarian and in English.
FOLLOWING AGENDA:
-
Report on the 2025 activities of the Equal Opportunities Committee
Submitter: Judit Nagy, Vice-Rector for Student Affairs
Bruno van Pottelsberghe: And we proceed with the following item on the agenda.
Report on the 2025 activities of the Equal Opportunities Committee and the submitter
is Judit Nagy, Vice-Rector for Student Affairs.
Judit Nagy: Yes, thank you very much. As you have seen in the report, the members
of the Equal Opportunities Committee expired in the beginning of year 2025. For this
reason, we had to recreate the Committee. It happened in the autumn, and this is
about the report on what they have done since then, during that remaining part of the
year. We had new members. They came from the Legal and Procurement Services
organisational unit, the disability coordinator was attending, we had members from
academic area, Corvinus Employee Council and also students have a representative
in the Committee. And the main task of them was to create the Gender Equality Plan
that the Senate was so kind to accept in December in a written voting. Next to this,
they also created the Student Regulation on Equal Opportunities and Equal
Treatment. It was also accepted in December by the Senate. And now they are
preparing the employee equal opportunities and equal treatment regulation, which
will come to you soon, but this is already for the year 2026. And my task was to
inform you about their activity in 2025. So thank you.
Bruno van Pottelsberghe: Thank you very much. Any comments, questions? No.
-
Information on the cancelled conference of the project titled "The V4
Region and the War in Ukraine: Lessons in Foreign Information
Manipulation and Interference"
Submitters: Bruno van Pottelsberghe, President-Rector


—————
4 | 10

Kata Apáti-Tóth, Chief Communications Officer
Bruno van Pottelsberghe: Then we go to the next information on the cancelled
conference on the project titled V4 Region. We all have received a letter by Eszter
Kirs. I think we don't need to reread the letter or you want to? No, okay. I'd like to first
to be a bit more precise with respect to some detail in your letter and then to reply to
it. So you said that it was planned for disseminate the research finding regarding the
22-23 events and Russian disinformation in the region, in Ukraine region. That was
indeed, so the event for March to June 2022. And the conference was originally
scheduled for 19th of March, next Thursday, I would like to correct that. I would like to
correct that. It was originally planned for May-June, 2025. That was the original
contract that we had with the Visegrád Fund. Then after a first request by the
research leader, it was delayed to maximum, I'm quoting the Visegrád Fund, the 31st
of December 2025. And then after an additional request from the research leader, it
was further delayed to before the end of March 2026. And the argument used to
justify this delay was, well I quote, the letter that was sent to the Visegrád Fund due
to intensive drone attacks on Ukraine from November to October 2025. And hence,
these drone attacks would lead to disinformation on the subject of the proposal. I
must confess I don't understand this argumentation of delay because if the event
which is under focus is May-June 2022, there is no reason why drone attacks would
change any type of information by 25. But this is just a very small detail that I wanted
to underline that the justification was unclear to me. So of course I take the full
responsibility. I had a discussion with András Rácz, who is the leader, and I propose
to read the letter that was sent to all stakeholders with the agreement of András
Rácz.
And of course to the leader of the Visegrád Fund and then to the regional academics
who are involved in this research project. So in this case, we had four letters, but they
are all the same.
Dear Executive Director, Linda Kapustova Helbichova,
Corvinus University of Budapest highly values research projects that are supported
by the International Visegrád Fund and is pleased to continue strengthening this
longstanding cooperation. Indeed, the university strongly values academic
excellence, internationalization and research collaboration with many ongoing
transnational projects. One such international project conducted at our university with
the support of the International Visegrád Fund is the research titled The V4 Region
and the War in Ukraine: lessons in foreign information manipulation and interference,
project number 22410425, which promises an insightful regional perspective on this
topic. In the meantime, the Russian-Ukrainian war has emerged as a significant
element in the current election campaign. In this context, it appears possible that the
research findings and even the topics could be interpreted or employed in ways that
intersect even inadvertently with the campaign activities. However rigorous the study
supported by the International Visegrád Fund is presenting its results at this particular
moment carries the risk of the work being jeopardized, drawing the university into a
sphere of day-to-day political maneuvering from any side in which we cannot
responsibly engage. Given the importance of safeguarding academic freedom and


—————
5 | 10

integrity, Corvinus University of Budapest seeks to avoid organizing any event that
might unintentionally give rise to perceptions of instrumentalization. We strongly
believe that a brief postponement could help the research team present the results of
the project in an environment where its independent, methodological rigor and
scholarly intent are less likely to be conflated with ongoing campaign activities. For
this reason, we would suggest postponing the planned research presentation event
and the dissemination of the video summarizing the project results to May with a
corresponding two months extension of the project implementation period. We are
aware that the project timeline has already been extended and appreciate the Fund's
flexibility in this regard. In light of the exceptional circumstances, we hope this could
be considered as a final one of adjustment to allow the planned outputs to be
delivered as foreseen. This proposal has been prepared in consultation with our
colleague and project leader, András Rácz. Should the Fund agree to this last
modification, our international partners and the experts involved in presenting the
result will be duly informed about this change. The university will cover any additional
cost that may arise, including those associated with arranging the new project
presentation event and the prolongation of the project activities. We appreciate your
understanding and apologize for any inconvenience caused.
Yours sincerely. And well, Tamás agreed to sign because I was abroad. I could not
sign it myself. So it was prepared in agreement with András Rácz. We sent the letter
and we received the answer from the Visegrád Fund, the leader and who said that
she completely understands and asked the project to be finished before the end of
the academic year and sees no problem to delaying it by a few weeks. And this is it.
If you want to add, yes, go ahead.
Eszter Kirs: Okay, thank you. Thank you very much for this very informative,
detailed introduction of the project and the background of the extension of the
project. But actually my question is more simple. So there was an event scheduled
for this Thursday, so 19th of March, we were also informed, I know that not the whole
university, but me too, I carved it into my calendar like, I don't know, three weeks ago
when this information was shared, that there was a draft prepared for press release,
that there will be this event on Thursday. Also project partners and speakers were
invited as far as I know their plane tickets were covered, paid, hotel rooms booked,
everything practically prepared for this event. And yesterday I was informed that on
Friday the initiative came from the top management and not from the project leader
that this event should be somehow, there should be a solution to make it sure that it's
not framed in a politically sensitive manner. I guess this is directly related to the
elections, upcoming elections in Hungary. So I see the logic, there are political
considerations. I see that. I understand that. But my question is still there. So who
was the one, the person from the top management who initiated at the project leader
the effective cancellation of this event, we can say that even if it's just postponed. It's
supposed to be had in the future at a certain point. But these speakers from
Bratislava, Prague were expecting to be here on Thursday. They were supposed to
be flying to Budapest on Wednesday and they were informed that they are not
welcome anymore. The event is canceled. The Visegrád Fund was informed about
that. I heard the letter. I know that the project leader then consented upon the
initiative from the top management. So my question is still there. If you can kindly


—————
6 | 10

answer that question, who was the person from the top management who initiated
that there should be some kind of solution around an academic event. This is an
academic event. This was a pre-planned event. Even a press release was drafted a
few weeks ago. All the foreign speakers were invited and made sure that they can fly
in. So it was all set, Visegrád Fund knew about it. So obviously there is a diplomatic
problematic situation around it. But that was specifically set even practically
organized everything prepared. There might have been details which have not been
arranged yet, but that is not relevant to the question who was the one from the top
management who basically asked a colleague of ours that an academic event should
be, I don't know what, I didn't listen to the conversation, but I don't know who
proposed what, cancellation, postponement, but I'm sure that even if it's about like
politically sensitive issues which is clearly disinformation, Russian disinformation is a
politically sensitive issue. I see that clearly, but it can be handled in a proper way
based on, I don't know, one and a half year of a project based research so that the
collected data can properly be presented without any kind of political involvement.
And here I have a different understanding on neutrality. I don't think that neutrality
justifies a decision to cancel any kind of academic event because then if it's
connected to political considerations, it's gonna be censorship based on political
grounds. And it's simple as that to me. And this is why I'm extremely curious because
this is the first case that I came across such an incident at this university. So I think
it's a really, really serious case and should be handled seriously. Who was the one
who proposed and how come such a situation we could get in that an academic
event is even postponed based on political considerations. Thank you.
Bruno van Pottelsberghe: Well, you mentioned the name diplomatic. There was
nothing diplomatic. It was purely internal discussion, but I give the floor to Kata.
Kata Apáti-Tóth: Thank you very much. I would like just to add some more aspect,
Eszter. It wasn't 100% what you told before because the project leader, the research
project leader wasn't 100% sure to have this event, this Thursday, they didn't even
invite all the academic audience. No release any official academic invitation. Yes, it
was only just a press invitation. They didn't even make it publish. Please don't laugh.
It happened because I was in touch with András and the project lead management
and they didn't even release the application form to our webpage. They didn't even
invite the academic audience to this research last Thursday and Friday. And of
course, we had a discussion and we tried to discover all of circumstances. So the
only thing that went out, it was a press invitation, not an invitation to the academic
audience. I think it's very important because you mentioned that everything was set

__Refined prompt__

You are an expert in analysing institutional meeting transcripts, especially Senate, board, committee, and academic governance meetings.

Your task is to analyse the supplied transcript and extract structured information about:

1. conversations and substantive discussions;
2. voting;
3. discussion segments;
4. concepts discussed;
5. actors participating in the discussions;
6. each actor's attitude toward each concept;
7. evidence supporting each attitude;
8. confidence in each extracted relationship;
9. an actor × concept attitude matrix summarising the results.

The analysis must be based exclusively on the supplied transcript. Do not use external knowledge or assumptions about the people, organisations, political positions, or events mentioned in the transcript.

---

# 1. Conversation detection

Set **`contains_conversation`** to **`1`** only when the text contains an actual substantive exchange between two or more actors.

Examples include:

- questions and answers;
- comments followed by responses;
- disagreement or agreement;
- discussion of a proposal;
- arguments and counterarguments;
- participants challenging or clarifying another participant's statement;
- participants expressing different views on the same issue.

Set **`contains_conversation`** to **`0`** if there is no substantive exchange.

Do NOT treat the following by themselves as a conversation:

- a speech or presentation by one person;
- reading an announcement;
- listing agenda items;
- procedural instructions;
- introductions;
- ceremonial remarks;
- simple acknowledgements such as "thank you";
- mentioning another person's opinion without engaging with it.

A meeting can contain voting without containing substantive conversation.

---

# 2. Voting detection

Set **`contains_voting`** to **`1`** when the text contains an actual or explicitly initiated voting procedure.

Examples include:

- a request to vote;
- a vote on an agenda item;
- a recorded vote or voting result;
- a motion being put to a vote;
- approval or rejection through voting;
- written or electronic voting;
- yes/no voting;
- abstentions;
- an explicit reference to a previous written vote.

Set **`contains_voting`** to **`0`** when voting is not present.

Do not infer voting merely because a decision, approval, adoption, or rejection is mentioned.

There must be textual evidence that voting occurred, was requested, or was explicitly referred to as voting.

---

# 3. Discussion segments

Divide the transcript into meaningful **`discussion_segments`**.

A discussion segment is a contiguous portion of the transcript dealing with one substantive issue, concept, proposal, question, or disagreement.

Do NOT create one segment for every speaker turn.

If several speakers discuss the same issue consecutively, group their contributions into one segment.

Start a new segment when the discussion clearly changes to another substantive issue.

For every segment provide:

- a unique **`segment_id`**;
- a short title;
- the approximate location in the transcript;
- the main topic;
- a concise summary;
- the actors participating;
- the concepts discussed.

Example:

{
"segment_id": "S3",
"title": "Postponement of the V4 conference",
"location": "Pages 4-10",
"summary": "Participants discuss the postponement of the conference, political sensitivity, academic freedom, institutional neutrality, and the role of university management.",
"actor_ids": ["A1", "A2", "A3"],
"concept_ids": ["C1", "C2", "C3"]
}

---

# 4. Concepts

A concept is a substantive issue, proposal, principle, decision, event, or topic that participants discuss.

Do not create a separate concept for every sentence.

Group semantically related statements into a single concept.

Prefer concise, meaningful concept names such as:

- "Postponement of the conference"
- "Academic freedom"
- "Political neutrality"
- "Political sensitivity of the research"
- "Scientific integrity"
- "Institutional reputational risk"
- "Political interference"
- "University censorship"

Do not automatically treat every noun mentioned in the transcript as a concept.

A concept should be something that participants actually discuss, evaluate, question, support, reject, or otherwise engage with.

If the same concept appears in multiple discussion segments, normally create only one concept and link it to all relevant segments.

Create separate concepts only when the issues are substantively distinct.

---

# 5. Actors

An actor is a person or clearly identifiable group that meaningfully participates in a discussion.

Use the actor's full name when available.

Examples:

- "Bruno van Pottelsberghe"
- "Eszter Kirs"
- "Kata Apáti-Tóth"
- "Mánuel László Mágó"
- "The Senate"

Do not include people who are merely mentioned but do not participate meaningfully.

Distinguish individuals from groups or institutions when the transcript supports this distinction.

Every actor receives a unique **`actor_id`**.

---

# 6. Actor-concept relationships

For every actor who meaningfully addresses a concept, create an **`actor_attitude`** relationship.

An actor does NOT need to have a relationship with every concept in a discussion segment.

Only create a relationship when the transcript contains evidence that the actor actually addressed the concept.

Each relationship must contain:

- actor;
- concept;
- attitude;
- confidence;
- evidence;
- discussion segment(s).

---

# 7. Attitude classification

Classify the actor's expressed attitude toward each concept using exactly one of:

### `"positive"`

The actor explicitly:

- supports;
- approves;
- agrees with;
- endorses;
- defends;
- favors;

the concept.

### `"negative"`

The actor explicitly:

- opposes;
- criticizes;
- rejects;
- objects to;
- condemns;
- expresses an unfavorable view;

toward the concept.

### `"neutral"`

The actor discusses, describes, explains, questions, or refers to the concept without expressing a clearly positive or negative attitude.

### `"mixed"`

The actor expresses both favorable and unfavorable views toward the same concept.

For example:

"I understand why the conference was postponed, but I strongly disagree with postponing it."

This is **`"mixed"`** toward the concept of postponement.

### `"unclear"`

There is insufficient evidence to reliably determine the actor's attitude.

Do not guess.

---

# 8. Important distinction: attitude vs factual statement

Do not classify an actor as positive or negative simply because they make a factual claim.

For example:

"The conference was postponed."

→ **`"neutral"`**

"The postponement was completely unnecessary."

→ **`"negative"`**

"I believe postponing the conference protects the university."

→ **`"positive"`**

Similarly:

"The university has academic freedom."

is not automatically positive toward the concept of academic freedom.

The actor must express an evaluative position for the attitude to be positive or negative.

---

# 9. Important distinction: object of the attitude

Be precise about WHAT the actor is expressing an attitude toward.

For example, an actor might:

- support academic freedom;
- oppose postponing a conference;
- support postponing the conference;
- oppose political interference;
- criticize the university's reasoning for postponing the conference.

These are different relationships.

Do not collapse them into a general statement such as:

"Actor X is positive about the conference."

Identify the actual concept being evaluated.

---

# 10. Complex and conditional positions

When an actor expresses a nuanced or conditional position, analyse the individual concepts separately.

Example:

"I agree that the topic is politically sensitive, but I don't agree that this justifies postponing the event."

Possible extraction:

- Political sensitivity → positive/agreeing
- Postponement of the event → negative

Do not automatically classify the entire speaker's contribution as simply positive or negative.

---

# 11. Evidence

Every actor-concept relationship MUST include evidence.

Evidence should:

- come exclusively from the supplied transcript;
- be a concise quotation or faithful paraphrase;
- directly support the assigned attitude;
- identify the relevant statement or argument.

Keep quotations short.

If several statements support the classification, provide a concise synthesis rather than reproducing a long passage.

Example:

{
"attitude": "negative",
"evidence": "Eszter describes the postponement as censorship based on political grounds and questions why an academic event should be postponed because of political considerations."
}

Do not invent evidence.

---

# 12. Confidence score

Assign a numerical **`confidence`** between **`0`** and **`1`** to every actor-concept relationship.

The confidence score represents how strongly the transcript supports the extracted relationship and attitude.

Use the following guidance:

- **`0.90–1.00`**: explicit and unambiguous statement;
- **`0.75–0.89`**: strong evidence, with minor interpretation required;
- **`0.50–0.74`**: plausible interpretation, but somewhat ambiguous;
- **`0.25–0.49`**: weak evidence;
- **`0.00–0.24`**: very little evidence.

Use **`"unclear"`** when evidence is insufficient rather than assigning an artificially high confidence score.

The confidence score measures confidence in the **extraction**, not whether the actor's statement is factually correct.

For example:

"I strongly oppose postponing the conference."

→ attitude: **`"negative"`**
→ confidence: approximately **`0.98`**

"I understand the concern, although I'm not sure postponement is necessary."

→ attitude: **`"mixed"`**
→ confidence: approximately **`0.85`**

---

# 13. Changes of position

If an actor's attitude toward a concept changes during the transcript, do NOT hide the change.

Create separate actor-concept relationships for the relevant discussion segments.

For example:

- S1: Actor supports proposal.
- S4: Actor later expresses concerns about proposal.

Represent this as separate segment-level observations and, where appropriate, an overall relationship marked **`"mixed"`**.

The output should preserve the evolution of the discussion.

---

# 14. Discussion-level extraction

For every discussion segment, identify:

- participating actors;
- concepts discussed;
- actor-concept attitudes;
- supporting evidence;
- confidence scores.

An actor can participate in a segment without expressing an attitude toward every concept in that segment.

Do not force missing relationships.

---

# 15. Actor × concept attitude matrix

In addition to the detailed evidence-based relationships, create an **`attitude_matrix`**.

The matrix must have:

- one row for each actor;
- one column for each concept;
- the corresponding attitude in each cell.

Use these values:

- **`positive`**
- **`negative`**
- **`neutral`**
- **`mixed`**
- **`unclear`**
- **`not_discussed`**

Use **`"not_discussed"`** when there is no evidence that the actor addressed the concept.

Do NOT use **`"neutral"`** simply because no attitude was found.

This distinction is important:

- **`"neutral"`** = the actor discussed the concept but did not express a positive or negative attitude.
- **`"not_discussed"`** = there is no evidence that the actor addressed the concept.

Example:

{
"attitude_matrix": {
"actors": [
{
"actor_id": "A1",
"actor": "Bruno van Pottelsberghe",
"attitudes": {
"C1": "positive",
"C2": "neutral",
"C3": "negative"
}
},
{
"actor_id": "A2",
"actor": "Eszter Kirs",
"attitudes": {
"C1": "negative",
"C2": "positive",
"C3": "not_discussed"
}
}
]
}
}

The matrix is a summary of the detailed actor-concept relationships.

Do not introduce information into the matrix that does not exist in the detailed evidence.

---

# 16. Matrix confidence

For every matrix cell that is not **`"not_discussed"`**, also provide the confidence score and the relevant discussion segment IDs.

Use a structured matrix representation rather than only a string value.

For example:

{
"actor_id": "A1",
"actor": "Bruno van Pottelsberghe",
"attitudes": {
"C1": {
"attitude": "positive",
"confidence": 0.94,
"segment_ids": ["S3"]
},
"C2": {
"attitude": "neutral",
"confidence": 0.88,
"segment_ids": ["S3", "S4"]
},
"C3": {
"attitude": "not_discussed",
"confidence": null,
"segment_ids": []
}
}
}

This makes the matrix traceable back to the original discussion.

---

# 17. Overall concept summary

For every concept, provide a concise summary of the positions expressed by the different actors.

Do not determine which actor is correct.

Do not rank actors.

Do not determine which position is preferable.

The purpose is to represent the discussion faithfully.

Example:

{
"concept_id": "C1",
"concept": "Postponement of the conference",
"summary_of_positions": "Some participants describe the postponement as a reasonable temporary measure to avoid political sensitivity, while others view it as inappropriate interference with an academic event."
}

When positions are disputed, attribute them to the relevant actors rather than presenting a disputed interpretation as an objective fact.

---

# 18. Voting details

If **`contains_voting`** is **`1`**, identify the voting events where possible.

For each voting event provide:

- **`vote_id`**;
- the subject being voted on;
- the relevant discussion segment;
- the stated proposal/resolution;
- any explicitly reported result;
- explicitly identified individual votes or abstentions;
- whether the result is known.

Do not invent vote counts.

For example:

{
"vote_id": "V1",
"subject": "Amendment of the Rules of Procedure of the Senate",
"segment_id": "S2",
"proposal": "Amend the Rules of Procedure in Hungarian and English.",
"result": "not explicitly reported",
"individual_votes": [
{
"actor_id": "A3",
"vote": "abstain"
}
]
}

If a vote is mentioned but the result is not available, use:

**`"result": "not explicitly reported"`**

Do not infer the result from subsequent statements unless the transcript explicitly establishes it.

---

# 19. Final JSON schema

Return ONLY valid JSON.

Do not return Markdown.

Do not return explanations outside the JSON.

Use exactly this overall structure:

{
"contains_conversation": 0,
"contains_voting": 0,

"discussion_segments": [
{
"segment_id": "S1",
"title": "Short discussion title",
"location": "Approximate location",
"summary": "Concise summary",
"actor_ids": ["A1", "A2"],
"concept_ids": ["C1", "C2"]
}
],

"actors": [
{
"actor_id": "A1",
"actor": "Full name"
}
],

"concepts_discussed": [
{
"concept_id": "C1",
"concept": "Concept name",
"description": "Concise description",
"summary_of_positions": "Concise neutral summary of the positions expressed",
"discussion_segment_ids": ["S1"],

```
  "actor_attitudes": [
    {
      "actor_id": "A1",
      "attitude": "positive",
      "confidence": 0.95,
      "evidence": "Concise supporting evidence",
      "discussion_segment_ids": ["S1"]
    }
  ]
}

```

],

"attitude_matrix": {
"actors": [
{
"actor_id": "A1",
"actor": "Full name",
"attitudes": {
"C1": {
"attitude": "positive",
"confidence": 0.95,
"segment_ids": ["S1"]
},
"C2": {
"attitude": "not_discussed",
"confidence": null,
"segment_ids": []
}
}
}
]
},

"voting_events": [
{
"vote_id": "V1",
"subject": "Subject of vote",
"segment_id": "S1",
"proposal": "Proposal being voted on",
"result": "Result if explicitly stated, otherwise 'not explicitly reported'",
"individual_votes": [
{
"actor_id": "A1",
"vote": "yes | no | abstain | unclear"
}
]
}
]
}

---

# 20. Empty-value rules

If there is no substantive discussion:

- **`contains_conversation`** = **`0`**
- **`discussion_segments`** = **`[]`**
- **`concepts_discussed`** = **`[]`**
- **`attitude_matrix.actors`** = **`[]`**

If there is no voting:

- **`contains_voting`** = **`0`**
- **`voting_events`** = **`[]`**

If there is discussion but no identifiable individual actors:

- use the identifiable group/institution as the actor where appropriate.

If a concept was discussed but an actor's attitude cannot be determined:

- use **`"unclear"`**.

If an actor did not discuss a concept:

- use **`"not_discussed"`** in the matrix.

Never substitute **`"neutral"`** for **`"not_discussed"`**.

---

# 21. Final quality-control checks

Before returning the JSON, verify:

1. Every **`concept_id`** referenced by a discussion segment exists in **`concepts_discussed`**.
2. Every **`actor_id`** referenced anywhere exists in **`actors`**.
3. Every segment ID referenced by an actor-concept relationship exists in **`discussion_segments`**.
4. Every concept in the attitude matrix exists in **`concepts_discussed`**.
5. Every actor in the attitude matrix exists in **`actors`**.
6. Every matrix attitude is supported by a corresponding detailed actor-concept relationship.
7. **`"not_discussed"`** is used when there is no evidence of discussion.
8. **`"neutral"`** is used only when the actor actually discusses the concept without expressing a positive or negative attitude.
9. Every positive, negative, mixed, or unclear classification has supporting evidence.
10. Every confidence score is between **`0`** and **`1`**.
11. No external knowledge has been introduced.
12. No actor has been assigned an attitude merely because another actor expressed that attitude.
13. No voting result has been invented.
14. The JSON is syntactically valid.

## Text to analyse

—————

[INSERT TRANSCRIPT HERE]

—————

| Actor                       | Ethics Code / Ethics Committee rules | Senate Rules amendment | Equal Opportunities / GEP |               V4 conference postponement | Institutional political neutrality | Academic freedom / scientific integrity |
| --------------------------- | -----------------------------------: | ---------------------: | ------------------------: | ---------------------------------------: | ---------------------------------: | --------------------------------------: |
| **Bruno van Pottelsberghe** |                               🟢 Pro |                 🟢 Pro |       🟢 Pro / supportive |                                   🟢 Pro |                             🟢 Pro |                    🟡 Mixed / qualified |
| **Gábor Toronyai**          |                               🟢 Pro |        ⚪ Not discussed |           ⚪ Not discussed |                          ⚪ Not discussed |                    ⚪ Not discussed |                                  🟢 Pro |
| **Gábor Klimkó**            |                      ⚪ Not discussed | 🟡 Qualified / abstain |           ⚪ Not discussed |                          ⚪ Not discussed |                    ⚪ Not discussed |                            🟡 Qualified |
| **Judit Nagy**              |                      ⚪ Not discussed |        ⚪ Not discussed |                    🟢 Pro |                          ⚪ Not discussed |                    ⚪ Not discussed |                         ⚪ Not discussed |
| **Eszter Kirs**             |                      ⚪ Not discussed |        ⚪ Not discussed |           ⚪ Not discussed |                                🔴 Contra |                          🔴 Contra |                                  🟢 Pro |
| **Kata Apáti-Tóth**         |                      ⚪ Not discussed |        ⚪ Not discussed |           ⚪ Not discussed |           🟢 Pro / supports postponement |                             🟢 Pro |                            🟡 Qualified |
| **Ágnes Szunomár**          |                      ⚪ Not discussed |        ⚪ Not discussed |           ⚪ Not discussed | 🔴 Contra / concerned about cancellation |                           🟡 Mixed |                                  🟢 Pro |
| **Mánuel László Mágó**      |                      ⚪ Not discussed |        ⚪ Not discussed |           ⚪ Not discussed |                                🔴 Contra |                          🔴 Contra |                         🟢 Strongly pro |
| **András Rácz**             |                      ⚪ Not discussed |        ⚪ Not discussed |           ⚪ Not discussed |                       🟡 Mixed / unclear |                 🟡 Mixed / unclear |               🟢 Presumably supportive* |
| **Senate as a body**        |                               🟢 Pro |                 🟢 Pro |                    🟢 Pro |        ⚪ No collective position recorded |  ⚪ No collective position recorded |       ⚪ No collective position recorded |

## Optinal chunking

In [ ]:
import pandas as pd
from Helper import Log

In [ ]:
df = pd.read_csv('senate_meeting_minutes\output\senate_meeting_minutes_hun_202609231622.csv')

In [ ]:
import os
import io

MAX_BYTES = 1 * 1024 * 1024  # 1 MB

part_number = 1
start = 0
n = len(df)

while start < n:
    # Grow the chunk until the next row would push us over 1 MB
    end = start + 1
    while end <= n:
        candidate = df.iloc[start:end]
        # Measure the exact size the JSON will have on disk
        buffer = io.StringIO()
        candidate.to_json(
            buffer,
            orient="records",
            force_ascii=False,
            indent=2,
        )
        size = len(buffer.getvalue().encode("utf-8"))
        if size > MAX_BYTES and end > start + 1:
            # Last row made it too big → drop it
            end -= 1
            break
        end += 1

    chunk = df.iloc[start:end]
    with Log.save_file(f"{WORK_DIR}/json/senate_meeting_minutes_hun_part{part_number}.json") as filename:
        chunk.to_json(
            filename,
            orient="records",
            force_ascii=False,
            indent=2,
        )

    start = end
    part_number += 1